#!/usr/bin/env node
// Generated by `npm run bundle` from src/ (tools/bundle.mjs). Do not edit; change src/ and rebuild.

// src/cli.ts
import { realpathSync as realpathSync2 } from "node:fs";
import { pathToFileURL } from "node:url";

// src/errors.ts
var UserError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "UserError";
  }
};
var SessionExpiredError = class extends UserError {
  constructor() {
    super("Session expired on this machine; run: mokkan login");
    this.name = "SessionExpiredError";
  }
};

// src/client.ts
var ApiError = class extends Error {
  constructor(status, code, message, body, retryAfterSeconds) {
    super(message);
    this.status = status;
    this.code = code;
    this.body = body;
    this.retryAfterSeconds = retryAfterSeconds;
    this.name = "ApiError";
  }
  status;
  code;
  body;
  retryAfterSeconds;
};
var NetworkError = class extends Error {
  constructor(message, cause) {
    super(message);
    this.cause = cause;
    this.name = "NetworkError";
  }
  cause;
};
var REFRESH_AHEAD_MS = 3600 * 1e3;
var CHECKOUT_TIMEOUT_MS = 3e4;
var MokkanClient = class {
  baseUrl;
  credentials;
  onCredentials;
  reloadCredentials;
  lock;
  onSessionExpired;
  onListChanged;
  fetchImpl;
  timeoutMs;
  signal;
  now;
  /** The in-flight refresh, shared by every caller: the server rotates refresh tokens and treats reuse as theft. */
  refreshing = null;
  constructor(opts) {
    this.baseUrl = opts.baseUrl.replace(/\/+$/, "");
    this.credentials = opts.credentials ?? null;
    this.onCredentials = opts.onCredentials;
    this.reloadCredentials = opts.reloadCredentials;
    this.lock = opts.lock ?? ((fn) => fn());
    this.onSessionExpired = opts.onSessionExpired;
    this.onListChanged = opts.onListChanged ?? (() => void 0);
    this.fetchImpl = opts.fetchImpl ?? fetch;
    this.timeoutMs = opts.timeoutMs ?? 5e3;
    this.signal = opts.signal;
    this.now = opts.now ?? (() => /* @__PURE__ */ new Date());
  }
  hasCredentials() {
    return this.credentials !== null;
  }
  get email() {
    return this.credentials?.email ?? null;
  }
  // ---- unauthenticated ----
  health() {
    return this.call("GET", "/health");
  }
  async registerStart(email) {
    await this.call("POST", "/auth/register/start", { email });
  }
  async registerComplete(email, otp, password) {
    const pair = await this.call("POST", "/auth/register/complete", { email, otp, password });
    this.onListChanged();
    return this.adopt(pair, email);
  }
  async login(email, password) {
    const pair = await this.call("POST", "/auth/login", { email, password });
    this.onListChanged();
    return this.adopt(pair, email);
  }
  /** Single-flight: concurrent callers share one /auth/refresh request instead of each rotating the same token. */
  refresh() {
    if (this.refreshing) return this.refreshing;
    const inFlight = this.refreshOnce().finally(() => {
      if (this.refreshing === inFlight) this.refreshing = null;
    });
    this.refreshing = inFlight;
    return inFlight;
  }
  /**
   * Cross-process safe rotation. The server revokes the whole token family when a refresh token is presented twice,
   * so before refreshing we re-read the credentials file: if another process already rotated, adopt its tokens.
   * The re-read, the refresh and the save run under an exclusive lock file so two processes can never both
   * present the same refresh token.
   */
  async refreshOnce() {
    const current = this.credentials;
    if (!current) throw new ApiError(401, "no_credentials", "Not logged in. Run: mokkan login");
    const rotatedElsewhere = () => {
      const stored = this.reloadCredentials?.() ?? null;
      return stored && stored.refresh_token !== current.refresh_token ? stored : null;
    };
    const early = rotatedElsewhere();
    if (early) return this.adoptStored(early);
    try {
      return await this.lock(async () => {
        const stored = rotatedElsewhere();
        if (stored) return this.adoptStored(stored);
        let pair;
        try {
          pair = await this.call("POST", "/auth/refresh", { refresh_token: current.refresh_token });
        } catch (err) {
          if (err instanceof ApiError && err.status === 401 && err.code === "invalid_token") {
            this.credentials = null;
            this.onSessionExpired?.();
            throw new SessionExpiredError();
          }
          throw err;
        }
        return this.adopt(pair, current.email);
      }, this.signal);
    } catch (err) {
      if (err instanceof SessionExpiredError) throw err;
      let stored = null;
      try {
        stored = rotatedElsewhere();
      } catch {
      }
      if (stored) return this.adoptStored(stored);
      throw err;
    }
  }
  /** Tokens another process already saved: use them without saving again. */
  adoptStored(stored) {
    this.credentials = stored;
    return stored;
  }
  // ---- authenticated ----
  async logout() {
    await this.authed("POST", "/auth/logout");
    this.credentials = null;
    this.onListChanged();
  }
  me() {
    return this.authed("GET", "/me");
  }
  heartbeat(source, sessionId) {
    return this.authed("POST", "/heartbeat", sessionId === void 0 ? { source } : { source, session_id: sessionId });
  }
  list(scope = "active") {
    return this.authed("GET", `/reminders?scope=${scope}`);
  }
  push(text, dueAt, clientId) {
    const body = { text };
    if (dueAt) body.due_at = dueAt.toISOString();
    if (clientId !== void 0) body.client_id = clientId;
    return this.changing(this.authed("POST", "/reminders", body));
  }
  /** Changes text and/or due_at (null clears it). Every 3rd successful edit costs a credit. */
  editReminder(id, patch, expectedVersion) {
    const body = {};
    if (patch.text !== void 0) body.text = patch.text;
    if (patch.due_at !== void 0) body.due_at = patch.due_at === null ? null : patch.due_at.toISOString();
    if (expectedVersion !== void 0) body.expected_version = expectedVersion;
    return this.changing(this.authed("PATCH", `/reminders/${encodeURIComponent(id)}`, body));
  }
  /** Starts a Stripe Checkout session for a credit pack (default pack when omitted). */
  checkout(pack) {
    return this.authed("POST", "/billing/checkout", pack === void 0 ? {} : { pack }, CHECKOUT_TIMEOUT_MS);
  }
  balance() {
    return this.authed("GET", "/billing/balance");
  }
  pop(expectedVersion) {
    return this.changing(this.authed("POST", "/reminders/pop", expectedVersion === void 0 ? {} : { expected_version: expectedVersion }));
  }
  dequeue(expectedVersion) {
    return this.changing(this.authed("POST", "/reminders/dequeue", expectedVersion === void 0 ? {} : { expected_version: expectedVersion }));
  }
  pending() {
    return this.authed("GET", "/reminders/pending");
  }
  deliver(ids) {
    return this.changing(this.authed("POST", "/reminders/deliver", { ids }));
  }
  ack(idsOrAll, expectedVersion) {
    const body = idsOrAll === "all" ? { all: true } : { ids: idsOrAll };
    if (expectedVersion !== void 0) body.expected_version = expectedVersion;
    return this.changing(this.authed("POST", "/reminders/ack", body));
  }
  // ---- internals ----
  async changing(request) {
    const result = await request;
    this.onListChanged();
    return result;
  }
  adopt(pair, email) {
    this.credentials = {
      server_url: this.baseUrl,
      email,
      access_token: pair.access_token,
      access_expires_at: pair.access_expires_at,
      refresh_token: pair.refresh_token,
      refresh_expires_at: pair.refresh_expires_at
    };
    this.onCredentials?.(this.credentials);
    return this.credentials;
  }
  async call(method, path5, body) {
    const res = await this.raw(method, path5, body);
    if (res.status >= 400) throw toApiError(res);
    return res.json;
  }
  async authed(method, path5, body, timeoutMs) {
    if (!this.credentials) throw new ApiError(401, "no_credentials", "Not logged in. Run: mokkan login");
    const expiresAt = Date.parse(this.credentials.access_expires_at);
    if (Number.isFinite(expiresAt) && expiresAt - this.now().getTime() < REFRESH_AHEAD_MS) {
      await this.refresh();
    }
    const sentToken = this.credentials.access_token;
    let res = await this.raw(method, path5, body, sentToken, timeoutMs);
    if (res.status === 401) {
      if (this.refreshing || this.credentials?.access_token === sentToken) await this.refresh();
      if (!this.credentials) throw toApiError(res);
      res = await this.raw(method, path5, body, this.credentials.access_token, timeoutMs);
    }
    if (res.status >= 400) throw toApiError(res);
    return res.json;
  }
  async raw(method, path5, body, token, timeoutMs = this.timeoutMs) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);
    const headers = { accept: "application/json" };
    if (body !== void 0) headers["content-type"] = "application/json";
    if (token) headers.authorization = `Bearer ${token}`;
    try {
      const res = await this.fetchImpl(`${this.baseUrl}${path5}`, {
        method,
        headers,
        body: body === void 0 ? void 0 : JSON.stringify(body),
        signal: this.signal ? AbortSignal.any([controller.signal, this.signal]) : controller.signal
      });
      const text = await res.text();
      let json = null;
      if (text !== "") {
        try {
          json = JSON.parse(text);
        } catch {
          json = { error: "bad_response", message: text.slice(0, 200) };
        }
      }
      const ra = Number(res.headers?.get("retry-after"));
      return { status: res.status, json, retryAfterSeconds: Number.isFinite(ra) && ra > 0 ? ra : void 0 };
    } catch (err) {
      const reason = controller.signal.aborted ? `timed out after ${timeoutMs} ms` : this.signal?.aborted ? "overall deadline exceeded" : err.message;
      throw new NetworkError(`Cannot reach ${this.baseUrl}: ${reason}`, err);
    } finally {
      clearTimeout(timer);
    }
  }
};
function toApiError(res) {
  const body = res.json ?? {};
  const code = typeof body.error === "string" ? body.error : "error";
  const message = typeof body.message === "string" ? body.message : `HTTP ${res.status}`;
  return new ApiError(res.status, code, message, res.json, res.retryAfterSeconds);
}

// src/credentials.ts
import {
  chmodSync,
  closeSync,
  existsSync,
  mkdirSync,
  openSync,
  readFileSync,
  renameSync,
  statSync,
  unlinkSync,
  writeFileSync,
  writeSync
} from "node:fs";
import { randomBytes } from "node:crypto";
import { homedir } from "node:os";
import path from "node:path";
var DEFAULT_SERVER_URL = "https://api.mokkan.dev";
var CredentialsPermissionError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "CredentialsPermissionError";
  }
};
var CredentialsCorruptError = class extends UserError {
  constructor(file) {
    super(`credentials file is corrupt: ${file}. Run: mokkan logout (or delete it) then mokkan login`);
    this.file = file;
    this.name = "CredentialsCorruptError";
  }
  file;
};
var REQUIRED_KEYS = ["server_url", "email", "access_token", "access_expires_at", "refresh_token", "refresh_expires_at"];
function configDir(env = process.env) {
  const base = env.XDG_CONFIG_HOME && env.XDG_CONFIG_HOME !== "" ? env.XDG_CONFIG_HOME : path.join(env.HOME && env.HOME !== "" ? env.HOME : homedir(), ".config");
  return path.join(base, "mokkan");
}
function credentialsPath(env = process.env) {
  return path.join(configDir(env), "credentials.json");
}
function credentialsLockPath(env = process.env) {
  return `${credentialsPath(env)}.lock`;
}
function hookLogPath(env = process.env) {
  return path.join(configDir(env), "hook.log");
}
function loadCredentials(env = process.env) {
  const file = credentialsPath(env);
  if (!existsSync(file)) return null;
  const mode = statSync(file).mode & 511;
  if (mode & 63) {
    throw new CredentialsPermissionError(`${file} is readable by other users (mode ${mode.toString(8)}). Fix with: chmod 600 ${file}`);
  }
  const text = readFileSync(file, "utf8");
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new CredentialsCorruptError(file);
  }
  if (typeof parsed !== "object" || parsed === null) throw new CredentialsCorruptError(file);
  const record = parsed;
  for (const key of REQUIRED_KEYS) {
    if (typeof record[key] !== "string") throw new CredentialsCorruptError(file);
  }
  return record;
}
function saveCredentials(creds, env = process.env) {
  const dir = configDir(env);
  mkdirSync(dir, { recursive: true, mode: 448 });
  chmodSync(dir, 448);
  const file = credentialsPath(env);
  const tmp = `${file}.${process.pid}.${randomBytes(6).toString("hex")}.tmp`;
  writeFileSync(tmp, `${JSON.stringify(creds, null, 2)}
`, { mode: 384 });
  chmodSync(tmp, 384);
  renameSync(tmp, file);
}
function clearCredentials(env = process.env) {
  const file = credentialsPath(env);
  if (existsSync(file)) unlinkSync(file);
}
function resolveServerUrl(creds, env = process.env) {
  const fromEnv = env.MOKKAN_SERVER_URL;
  const url = fromEnv && fromEnv !== "" ? fromEnv : creds?.server_url ?? DEFAULT_SERVER_URL;
  return url.replace(/\/+$/, "");
}
var CredentialsLockError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "CredentialsLockError";
  }
};
async function withCredentialsLock(env, fn, opts = {}) {
  const { signal, timeoutMs = 5e3, pollMs = 50, staleMs = 3e4 } = opts;
  const dir = configDir(env);
  mkdirSync(dir, { recursive: true, mode: 448 });
  const file = credentialsLockPath(env);
  const owner = `${process.pid} ${randomBytes(8).toString("hex")}
`;
  const deadline = Date.now() + timeoutMs;
  for (; ; ) {
    try {
      const fd = openSync(file, "wx", 384);
      try {
        writeSync(fd, owner);
      } finally {
        closeSync(fd);
      }
      break;
    } catch (err) {
      if (err.code !== "EEXIST") throw err;
    }
    try {
      if (Date.now() - statSync(file).mtimeMs > staleMs) {
        unlinkSync(file);
        continue;
      }
    } catch (err) {
      if (err.code === "ENOENT") continue;
      throw err;
    }
    if (signal?.aborted) throw new CredentialsLockError(`Gave up waiting for ${file}: deadline exceeded`);
    if (Date.now() >= deadline) {
      throw new CredentialsLockError(`Timed out after ${timeoutMs} ms waiting for ${file} (another mokkan process is refreshing the session; if none is running, delete the file)`);
    }
    await new Promise((resolve) => setTimeout(resolve, pollMs));
  }
  try {
    return await fn();
  } finally {
    try {
      if (readFileSync(file, "utf8") === owner) unlinkSync(file);
    } catch {
    }
  }
}

// src/prompt.ts
import { createInterface } from "node:readline";
import { Writable } from "node:stream";
function promptLine(question, hidden) {
  if (!process.stdin.isTTY || !process.stdout.isTTY) {
    return Promise.reject(new Error("Interactive input required; run this command in a terminal"));
  }
  let muted = false;
  const output = new Writable({
    write(chunk, _encoding, callback) {
      if (!muted) process.stdout.write(chunk);
      callback();
    }
  });
  const rl = createInterface({ input: process.stdin, output, terminal: true });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      if (hidden) process.stdout.write("\n");
      resolve(answer.trim());
    });
    muted = hidden;
  });
}
async function readAllStdin() {
  if (process.stdin.isTTY) return "";
  const chunks = [];
  for await (const chunk of process.stdin) chunks.push(chunk);
  return Buffer.concat(chunks).toString("utf8");
}

// src/commands/auth.ts
var EMAIL_RE = /^[^\s@]+@[^\s@]+$/;
var MIN_PASSWORD_LENGTH = 10;
async function requireEmail(ctx, given, usage) {
  const email = given ?? (ctx.io.isTTY ? await ctx.io.prompt("Email: ", false) : "");
  if (!EMAIL_RE.test(email)) throw new UserError(`Provide an email address. Usage: ${usage}`);
  return email;
}
async function requirePassword(ctx, question) {
  const fromEnv = ctx.io.env.MOKKAN_PASSWORD;
  if (fromEnv && fromEnv !== "") return fromEnv;
  if (!ctx.io.isTTY) throw new UserError("A password is needed: run this in a terminal, or set MOKKAN_PASSWORD");
  return ctx.io.prompt(question, true);
}
async function requireOtp(ctx, email) {
  const flag = ctx.flags.otp;
  if (typeof flag === "string" && flag !== "") return flag;
  if (!ctx.io.isTTY) throw new UserError(`Provide the code: mokkan register --complete ${email} --otp <code>`);
  return ctx.io.prompt("One-time code: ", false);
}
async function registerCommand(ctx, args) {
  const { io, client, flags } = ctx;
  const email = await requireEmail(ctx, args[0], "mokkan register you@example.com");
  if (flags.complete !== true) {
    await client.registerStart(email);
    io.stdout(`One-time code sent to ${email}. (Dev server: read it from GET /dev/outbox?to=${email} or server/outbox.jsonl.)
`);
    if (flags.start === true) return 0;
    if (!io.isTTY) {
      io.stdout(`Finish in a terminal: mokkan register --complete ${email}
`);
      return 0;
    }
  }
  const otp = await requireOtp(ctx, email);
  const password = await requirePassword(ctx, `New password (min ${MIN_PASSWORD_LENGTH} chars): `);
  if (password.length < MIN_PASSWORD_LENGTH) throw new UserError(`Password must be at least ${MIN_PASSWORD_LENGTH} characters`);
  const creds = await client.registerComplete(email, otp, password);
  io.stdout(`Registered and logged in as ${creds.email} (${client.baseUrl}).
`);
  return 0;
}
async function loginCommand(ctx, args) {
  const email = await requireEmail(ctx, args[0], "mokkan login you@example.com");
  const fromEnv = ctx.io.env.MOKKAN_PASSWORD;
  if (!ctx.io.isTTY && (fromEnv === void 0 || fromEnv === "")) {
    ctx.io.stdout(`Finish in a terminal: mokkan login ${email}
`);
    return 0;
  }
  const password = await requirePassword(ctx, "Password: ");
  const creds = await ctx.client.login(email, password);
  ctx.io.stdout(`Logged in as ${creds.email} (${ctx.client.baseUrl}).
`);
  return 0;
}
async function logoutCommand(ctx) {
  if (!ctx.client.hasCredentials()) {
    ctx.io.stdout("Not logged in.\n");
    return 0;
  }
  try {
    await ctx.client.logout();
  } catch (err) {
    if (!(err instanceof NetworkError) && !(err instanceof ApiError)) throw err;
  }
  clearCredentials(ctx.io.env);
  ctx.io.stdout("Logged out.\n");
  return 0;
}
async function statusCommand(ctx) {
  const { io, client } = ctx;
  if (!client.hasCredentials()) {
    io.stdout(`Server: ${client.baseUrl}
Not logged in. Run: mokkan login
`);
    return 0;
  }
  const [me, list, pending] = await Promise.all([client.me(), client.list("active"), client.pending()]);
  if (ctx.json) {
    io.stdout(`${JSON.stringify({ server_url: client.baseUrl, me, active: list.reminders.length, due: pending.due.length, awaiting_ack: pending.awaiting_ack.length })}
`);
    return 0;
  }
  io.stdout([
    `Server: ${client.baseUrl}`,
    `Account: ${me.email}`,
    ...typeof me.credit_balance === "number" ? [`Credits: ${me.credit_balance}`] : [],
    `Session: ${me.session_active ? "active" : "inactive"} (last heartbeat ${me.last_heartbeat_at ?? "never"})`,
    `Active reminders: ${list.reminders.length}`,
    `Due now: ${pending.due.length}, awaiting ack: ${pending.awaiting_ack.length}`,
    ""
  ].join("\n"));
  return 0;
}

// src/format.ts
function shortId(id) {
  return id.slice(0, 8);
}
function formatRelative(target, now) {
  const diff = Math.round((target.getTime() - now.getTime()) / 1e3);
  const abs = Math.abs(diff);
  const unit = abs >= 86400 ? `${Math.floor(abs / 86400)}d` : abs >= 3600 ? `${Math.floor(abs / 3600)}h` : abs >= 60 ? `${Math.floor(abs / 60)}m` : `${abs}s`;
  return diff >= 0 ? `in ${unit}` : `${unit} ago`;
}
function formatReminderLine(r) {
  return `- [${shortId(r.id)}] ${r.text}${r.due_at ? ` (due ${r.due_at})` : ""}`;
}
function formatList(reminders, now) {
  if (reminders.length === 0) return "No reminders.\n";
  const lines = reminders.map((r, i) => {
    const due = r.due_at ? `  due ${r.due_at} (${formatRelative(new Date(r.due_at), now)})` : "";
    return `${String(i + 1).padStart(2)}. [${shortId(r.id)}] ${r.state.padEnd(12)} ${r.text}${due}`;
  });
  return `${lines.join("\n")}
`;
}
var ACK_HINT = "run /mokkan ack <id> or /mokkan ack all";
function formatPending(p) {
  if (p.due.length === 0 && p.awaiting_ack.length === 0) return "";
  const lines = ["Reminders (mokkan):"];
  for (const r of p.due) lines.push(formatReminderLine(r));
  if (p.awaiting_ack.length > 0) {
    lines.push(`${p.awaiting_ack.length} reminder(s) awaiting acknowledgment \u2014 ${ACK_HINT}`);
  }
  return `${lines.join("\n")}
`;
}

// src/commands/list.ts
async function listCommand(ctx) {
  const res = await ctx.client.list(ctx.flags.all === true ? "all" : "active");
  ctx.io.stdout(ctx.json ? `${JSON.stringify(res)}
` : formatList(res.reminders, ctx.now()));
  return 0;
}
async function doneCommand(ctx) {
  const res = await ctx.client.list("done");
  ctx.io.stdout(ctx.json ? `${JSON.stringify(res)}
` : formatList(res.reminders, ctx.now()));
  return 0;
}
async function pendingCommand(ctx) {
  const res = await ctx.client.pending();
  if (ctx.json) {
    ctx.io.stdout(`${JSON.stringify(res)}
`);
    return 0;
  }
  ctx.io.stdout(formatPending(res) || "Nothing pending.\n");
  return 0;
}

// src/duration.ts
var DURATION_RE = /^(?:(\d+)d)?(?:(\d+)h)?(?:(\d+)m)?(?:(\d+)s)?$/;
function parseDuration(input) {
  const s = input.trim();
  const m = DURATION_RE.exec(s);
  if (!s || !m || m.slice(1).every((part) => part === void 0)) {
    throw new Error(`Invalid duration "${input}" (examples: 30s, 10m, 2h, 1d, 1h30m)`);
  }
  const [d, h, min, sec] = m.slice(1).map((part) => part === void 0 ? 0 : Number(part));
  return d * 86400 + h * 3600 + min * 60 + sec;
}

// src/commands/mutate.ts
async function pushCommand(ctx, args) {
  const text = args.join(" ").trim();
  if (text === "") throw new UserError("Usage: mokkan push <text>");
  const res = await ctx.client.push(text);
  ctx.io.stdout(ctx.json ? `${JSON.stringify(res)}
` : `Pushed [${shortId(res.reminder.id)}] ${res.reminder.text}
`);
  return 0;
}
async function takeCommand(ctx, end) {
  try {
    const res = end === "pop" ? await ctx.client.pop() : await ctx.client.dequeue();
    const verb = end === "pop" ? "Popped" : "Dequeued";
    ctx.io.stdout(ctx.json ? `${JSON.stringify(res)}
` : `${verb} [${shortId(res.reminder.id)}] ${res.reminder.text}
`);
    return 0;
  } catch (err) {
    if (err instanceof ApiError && err.code === "empty") {
      ctx.io.stdout(ctx.json ? `${JSON.stringify({ error: "empty", message: "List is empty." })}
` : "List is empty.\n");
      return 1;
    }
    throw err;
  }
}
async function inCommand(ctx, args) {
  if (args.length < 2) throw new UserError("Usage: mokkan in <duration> <text>   (e.g. mokkan in 30m call mom)");
  let seconds;
  try {
    seconds = parseDuration(args[0]);
  } catch (err) {
    throw new UserError(err.message);
  }
  const text = args.slice(1).join(" ").trim();
  if (text === "") throw new UserError("Usage: mokkan in <duration> <text>");
  const now = ctx.now();
  const dueAt = new Date(now.getTime() + seconds * 1e3);
  if (!Number.isFinite(dueAt.getTime())) throw new UserError("duration is too large");
  const res = await ctx.client.push(text, dueAt);
  ctx.io.stdout(ctx.json ? `${JSON.stringify(res)}
` : `Scheduled [${shortId(res.reminder.id)}] "${res.reminder.text}" for ${dueAt.toISOString()} (${formatRelative(dueAt, now)})
`);
  return 0;
}
function resolvePrefixes(reminders, prefixes, listCommand2 = "mokkan list") {
  const ids = /* @__PURE__ */ new Set();
  for (const prefix of prefixes) {
    const matches = reminders.filter((r) => r.id.startsWith(prefix));
    if (matches.length === 0) throw new UserError(`No ${listCommand2 === "mokkan list" ? "active " : ""}reminder matches "${prefix}" (run: ${listCommand2})`);
    if (matches.length > 1) throw new UserError(`"${prefix}" is ambiguous: ${matches.map((r) => shortId(r.id)).sort().join(", ")}`);
    ids.add(matches[0].id);
  }
  return [...ids];
}
async function ackCommand(ctx, args) {
  if (args.length === 0) throw new UserError("Usage: mokkan ack <id-prefix>... | mokkan ack all");
  let acknowledged;
  if (args[0] === "all") {
    acknowledged = (await ctx.client.ack("all")).acknowledged;
  } else {
    acknowledged = await ackWithRetry(ctx, args);
  }
  ctx.io.stdout(ctx.json ? `${JSON.stringify({ acknowledged })}
` : `Acknowledged ${acknowledged.length} reminder(s).
`);
  return 0;
}
async function ackWithRetry(ctx, prefixes) {
  for (let attempt = 0; ; attempt++) {
    const list = await ctx.client.list("active");
    const ids = resolvePrefixes(list.reminders, prefixes);
    try {
      return (await ctx.client.ack(ids, list.version)).acknowledged;
    } catch (err) {
      if (err instanceof ApiError && err.code === "stale" && attempt === 0) continue;
      throw err;
    }
  }
}
var POSITION_RE = /^\d{1,3}$/;
var ISO_WITH_ZONE_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2}(\.\d{1,9})?)?(Z|[+-]\d{2}:?\d{2})$/i;
var EDIT_USAGE = "Usage: mokkan edit <n|id> [--all] [--in <duration> | --at <iso> | --clear-due] [new text...]";
function listCommandName(scope) {
  return scope === "all" ? "mokkan list --all" : "mokkan list";
}
function resolveEditTarget(list, target) {
  if (target.kind === "prefix") {
    return resolvePrefixes(list, [target.prefix], "mokkan list --all")[0];
  }
  if (target.n < 1 || target.n > list.length) {
    throw new UserError(`There is no reminder number ${target.n} in \`${listCommandName(target.scope)}\` (it shows ${list.length}).`);
  }
  return list[target.n - 1].id;
}
function buildEditPatch(ctx, words, now) {
  const { text: textFlag, in: inFlag, at, "clear-due": clearDue } = ctx.flags;
  for (const [name, value] of [["text", textFlag], ["in", inFlag], ["at", at]]) {
    if (value === "") throw new UserError(`--${name} needs a value.
${EDIT_USAGE}`);
  }
  const timeFlags = [inFlag !== void 0, at !== void 0, clearDue === true].filter(Boolean).length;
  if (timeFlags > 1) throw new UserError("Use either --in, --at or --clear-due, not several.");
  const positionalText = words.join(" ").trim();
  if (textFlag !== void 0 && words.length > 0) {
    throw new UserError(`Give the new text either after the target or with --text, not both.
${EDIT_USAGE}`);
  }
  const rawText = textFlag !== void 0 ? String(textFlag).trim() : positionalText;
  if (textFlag !== void 0 && rawText === "") throw new UserError("--text must not be empty.");
  if (rawText === "" && timeFlags === 0) {
    throw new UserError(`There is nothing to change: give new text and/or --in, --at or --clear-due.
${EDIT_USAGE}`);
  }
  const patch = {};
  if (rawText !== "") patch.text = rawText;
  if (inFlag !== void 0) {
    let seconds;
    try {
      seconds = parseDuration(String(inFlag));
    } catch (err) {
      throw new UserError(err.message);
    }
    const due = new Date(now.getTime() + seconds * 1e3);
    if (!Number.isFinite(due.getTime())) throw new UserError("duration is too large");
    patch.due_at = due;
  } else if (at !== void 0) {
    const due = new Date(String(at));
    if (!ISO_WITH_ZONE_RE.test(String(at)) || Number.isNaN(due.getTime())) {
      throw new UserError(`Invalid --at "${String(at)}" (use an ISO time with a zone, such as 2026-10-01T09:00:00Z or 2026-10-01T11:00:00+02:00)`);
    }
    patch.due_at = due;
  } else if (clearDue === true) {
    patch.due_at = null;
  }
  return patch;
}
async function editCommand(ctx, args) {
  if (args.length === 0) throw new UserError(EDIT_USAGE);
  const now = ctx.now();
  const patch = buildEditPatch(ctx, args.slice(1), now);
  const target = POSITION_RE.test(args[0]) ? { kind: "number", n: Number(args[0]), scope: ctx.flags.all === true ? "all" : "active" } : { kind: "prefix", prefix: args[0] };
  const scope = target.kind === "number" ? target.scope : "all";
  let list = await ctx.client.list(scope);
  const id = resolveEditTarget(list.reminders, target);
  for (let attempt = 0; ; attempt++) {
    try {
      const res = await ctx.client.editReminder(id, patch, list.version);
      const r = res.reminder;
      ctx.io.stdout(ctx.json ? `${JSON.stringify(res)}
` : `Edited [${shortId(r.id)}] ${r.text}${r.due_at ? ` (due ${r.due_at}, ${formatRelative(new Date(r.due_at), now)})` : ""}
`);
      return 0;
    } catch (err) {
      if (err instanceof ApiError && err.code === "not_editable") {
        throw new UserError("This reminder was already shown or emailed, so --in/--at/--clear-due no longer apply (its text can still be edited).");
      }
      if (!(err instanceof ApiError && err.code === "stale" && attempt === 0)) throw err;
    }
    list = await ctx.client.list(scope);
    if (target.kind === "number") {
      const current = list.reminders[target.n - 1];
      if (current?.id !== id) throw new UserError(`The list changed; run ${listCommandName(target.scope)} and try again.`);
    }
  }
}

// src/commands/billing.ts
import { spawn as nodeSpawn } from "node:child_process";
function isTrustedCheckoutUrl(url) {
  let u;
  try {
    u = new URL(url);
  } catch {
    return false;
  }
  const host = u.hostname.toLowerCase();
  return u.protocol === "https:" && (host === "checkout.stripe.com" || host.endsWith(".stripe.com"));
}
function openUrlDetached(url, platform = process.platform, env = process.env, spawn2 = nodeSpawn) {
  if (!isTrustedCheckoutUrl(url)) return false;
  let cmd;
  let args;
  if (platform === "darwin") {
    cmd = "open";
    args = [url];
  } else if (platform === "win32") {
    cmd = "rundll32";
    args = ["url.dll,FileProtocolHandler", url];
  } else {
    if (!env.DISPLAY && !env.WAYLAND_DISPLAY) return false;
    cmd = "xdg-open";
    args = [url];
  }
  try {
    const child = spawn2(cmd, args, { detached: true, stdio: "ignore", windowsHide: true, env });
    child.on("error", () => void 0);
    child.unref();
    return true;
  } catch {
    return false;
  }
}
async function buyCommand(ctx) {
  if (ctx.flags.pack === "") throw new UserError("--pack needs a value.\nUsage: mokkan buy [--pack <key>] [--no-open]");
  const pack = typeof ctx.flags.pack === "string" ? ctx.flags.pack : void 0;
  let res;
  try {
    res = await ctx.client.checkout(pack);
  } catch (err) {
    if (err instanceof ApiError && err.status === 404) throw new UserError("Billing is not enabled on this server.");
    throw err;
  }
  const wanted = ctx.flags["no-open"] !== true;
  const trusted = isTrustedCheckoutUrl(res.url);
  if (wanted && trusted) {
    try {
      ctx.io.openUrl?.(res.url);
    } catch {
    }
  }
  if (ctx.json) {
    ctx.io.stdout(`${JSON.stringify(res)}
`);
    return 0;
  }
  let how;
  if (!wanted) how = "Open the link above in your browser to pay.";
  else if (trusted) how = "Opening it in your browser (open the link above if nothing appears).";
  else how = "This link was not opened automatically because it is not a Stripe Checkout (https://checkout.stripe.com) address. Check it before opening it.";
  ctx.io.stdout([
    `Checkout: ${res.url}`,
    how,
    "When the payment completes, run `mokkan balance` to see your credits.",
    ""
  ].join("\n"));
  return 0;
}
async function balanceCommand(ctx) {
  const res = await ctx.client.balance();
  if (ctx.json) {
    ctx.io.stdout(`${JSON.stringify(res)}
`);
    return 0;
  }
  const lines = [`Balance: ${res.balance} ${Math.abs(res.balance) === 1 ? "credit" : "credits"}`];
  if (res.ledger.length === 0) {
    lines.push("No transactions yet.");
  } else {
    lines.push("", "Recent transactions (UTC):");
    for (const e of res.ledger) {
      const when = e.created_at.replace("T", " ").slice(0, 16);
      const delta = e.delta > 0 ? `+${e.delta}` : String(e.delta);
      lines.push(`  ${when}  ${delta.padStart(6)}  ${e.reason}`);
    }
  }
  ctx.io.stdout(`${lines.join("\n")}
`);
  return 0;
}

// src/commands/heartbeat.ts
async function heartbeatCommand(ctx) {
  const source = typeof ctx.flags.source === "string" && ctx.flags.source !== "" ? ctx.flags.source : "cli";
  const res = await ctx.client.heartbeat(source);
  ctx.io.stdout(ctx.json ? `${JSON.stringify(res)}
` : `Heartbeat sent (${source}); session active until ${res.active_until}.
`);
  return 0;
}

// src/hooks.ts
import { appendFileSync, mkdirSync as mkdirSync2, readFileSync as readFileSync2, writeFileSync as writeFileSync2 } from "node:fs";
import path2 from "node:path";
var HOOK_BUDGET_MS = 8e3;
var DELIVER_MIN_REMAINING_MS = 1500;
var NOT_LOGGED_IN_LOG_INTERVAL_MS = 3600 * 1e3;
function parseHookInput(raw) {
  if (raw.trim() === "") return {};
  try {
    const value = JSON.parse(raw);
    return typeof value === "object" && value !== null ? value : {};
  } catch {
    return {};
  }
}
function formatStopDecision(due) {
  const reason = [
    "Reminders due (from the mokkan server):",
    ...due.map(formatReminderLine),
    `Tell the user these reminders verbatim, then remind them to ${ACK_HINT}. Then stop.`
  ].join("\n");
  const systemMessage = `${due.length} reminder(s) due \u2014 see reply`;
  return `${JSON.stringify({ decision: "block", reason, systemMessage })}
`;
}
function appendHookLog(env, kind, message) {
  const file = hookLogPath(env);
  mkdirSync2(path2.dirname(file), { recursive: true, mode: 448 });
  appendFileSync(file, `${(/* @__PURE__ */ new Date()).toISOString()} ${kind} ${message}
`, { mode: 384 });
}
function notifiedMarkerPath(env, suffix = "") {
  return `${hookLogPath(env)}${suffix}.notified`;
}
function notifiedRecently(env, suffix = "") {
  try {
    const at = Date.parse(readFileSync2(notifiedMarkerPath(env, suffix), "utf8").trim());
    const age = Date.now() - at;
    return Number.isFinite(at) && age >= 0 && age < NOT_LOGGED_IN_LOG_INTERVAL_MS;
  } catch {
    return false;
  }
}
function markNotified(env, suffix = "") {
  writeFileSync2(notifiedMarkerPath(env, suffix), `${(/* @__PURE__ */ new Date()).toISOString()}
`, { mode: 384 });
}
function safeAppendHookLog(env, kind, err) {
  try {
    if (err instanceof SessionExpiredError) {
      appendHookLog(env, kind, "session expired; run: mokkan login");
      markNotified(env);
      return;
    }
    if (err instanceof ApiError && err.code === "no_credentials") {
      if (notifiedRecently(env)) return;
      appendHookLog(env, kind, err.message);
      markNotified(env);
      return;
    }
    if (err instanceof ApiError && err.status === 402) {
      if (notifiedRecently(env, ".402")) return;
      appendHookLog(env, kind, err.message);
      markNotified(env, ".402");
      return;
    }
    appendHookLog(env, kind, err instanceof Error ? err.message : String(err));
  } catch {
  }
}
async function runHook(ctx, kind, input, deadlineAt = Infinity) {
  const { client } = ctx;
  const deliver = async (ids) => {
    if (ids.length > 0 && deadlineAt - Date.now() >= DELIVER_MIN_REMAINING_MS) await client.deliver(ids);
  };
  await client.heartbeat("claude-code", input.session_id);
  const pending = await client.pending();
  const dueIds = pending.due.map((r) => r.id);
  if (kind === "session-start") {
    const block = formatPending(pending);
    await deliver(dueIds);
    return block;
  }
  if (input.stop_hook_active === true || dueIds.length === 0) return "";
  await deliver(dueIds);
  return formatStopDecision(pending.due);
}
async function hookCommand(ctx, args, deadlineAt = Infinity) {
  const kind = args[0];
  if (kind !== "session-start" && kind !== "stop") throw new UserError("Usage: mokkan hook session-start|stop");
  try {
    const input = parseHookInput(await ctx.io.readStdin());
    ctx.io.stdout(await runHook(ctx, kind, input, deadlineAt));
  } catch (err) {
    safeAppendHookLog(ctx.io.env, kind, err);
  }
  return 0;
}

// src/watcher.ts
var DEFAULT_INTERVAL_SECONDS = 60;
var MIN_INTERVAL_SECONDS = 5;
async function watchOnce(ctx) {
  await ctx.client.heartbeat("watcher");
  const pending = await ctx.client.pending();
  if (pending.due.length === 0) return 0;
  ctx.io.stdout(`${ctx.now().toISOString()} reminders due:
${pending.due.map(formatReminderLine).join("\n")}
`);
  await ctx.client.deliver(pending.due.map((r) => r.id));
  return pending.due.length;
}
async function watchCommand(ctx) {
  const raw = ctx.flags.interval;
  const interval = raw === void 0 ? DEFAULT_INTERVAL_SECONDS : Number(raw);
  if (!Number.isInteger(interval) || interval < MIN_INTERVAL_SECONDS) {
    throw new UserError(`--interval must be a whole number of seconds, at least ${MIN_INTERVAL_SECONDS}`);
  }
  if (!ctx.client.hasCredentials()) throw new UserError("Not logged in. Run: mokkan login");
  const once = ctx.flags.once === true;
  const stop = new AbortController();
  const onSignal = () => {
    stop.abort();
  };
  process.once("SIGINT", onSignal);
  process.once("SIGTERM", onSignal);
  try {
    if (!once) ctx.io.stderr(`mokkan watch: polling ${ctx.client.baseUrl} every ${interval}s (Ctrl-C to stop)
`);
    while (!stop.signal.aborted) {
      try {
        await watchOnce(ctx);
      } catch (err) {
        if (err instanceof ApiError && err.code === "no_credentials" || err instanceof SessionExpiredError) throw err;
        ctx.io.stderr(`${ctx.now().toISOString()} watch error: ${err instanceof Error ? err.message : String(err)}
`);
      }
      if (once) break;
      await ctx.io.sleep(interval * 1e3, stop.signal);
    }
  } finally {
    process.off("SIGINT", onSignal);
    process.off("SIGTERM", onSignal);
  }
  return 0;
}

// src/status-cache.ts
import { chmodSync as chmodSync2, closeSync as closeSync2, mkdirSync as mkdirSync3, openSync as openSync2, readFileSync as readFileSync3, renameSync as renameSync2, statSync as statSync2, unlinkSync as unlinkSync2, writeFileSync as writeFileSync3, writeSync as writeSync2 } from "node:fs";
import { randomBytes as randomBytes2 } from "node:crypto";
import path3 from "node:path";
var REFRESH_LOCK_STALE_MS = 15e3;
function statusCachePath(env = process.env) {
  return path3.join(configDir(env), "status.json");
}
function refreshLockPath(env) {
  return `${statusCachePath(env)}.lock`;
}
function readStatusCache(env = process.env) {
  try {
    const value = JSON.parse(readFileSync3(statusCachePath(env), "utf8"));
    if (value?.v !== 2 || typeof value.server_url !== "string" || typeof value.email !== "string" || typeof value.attempted_at !== "string" || !Array.isArray(value.reminders)) return null;
    return value;
  } catch {
    return null;
  }
}
function writeStatusCache(cache, env = process.env) {
  const dir = configDir(env);
  mkdirSync3(dir, { recursive: true, mode: 448 });
  const file = statusCachePath(env);
  const tmp = `${file}.${process.pid}.${randomBytes2(6).toString("hex")}.tmp`;
  writeFileSync3(tmp, `${JSON.stringify(cache)}
`, { mode: 384 });
  chmodSync2(tmp, 384);
  renameSync2(tmp, file);
}
function invalidateStatusCache(env = process.env) {
  try {
    unlinkSync2(statusCachePath(env));
  } catch {
  }
}
function refreshInFlight(env = process.env) {
  try {
    return Date.now() - statSync2(refreshLockPath(env)).mtimeMs < REFRESH_LOCK_STALE_MS;
  } catch {
    return false;
  }
}
function tryAcquireRefreshLock(env = process.env) {
  const file = refreshLockPath(env);
  mkdirSync3(configDir(env), { recursive: true, mode: 448 });
  const owner = `${process.pid} ${randomBytes2(8).toString("hex")}
`;
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const fd = openSync2(file, "wx", 384);
      try {
        writeSync2(fd, owner);
      } finally {
        closeSync2(fd);
      }
      return () => {
        try {
          if (readFileSync3(file, "utf8") === owner) unlinkSync2(file);
        } catch {
        }
      };
    } catch (err) {
      if (err.code !== "EEXIST") throw err;
    }
    if (refreshInFlight(env)) return null;
    try {
      unlinkSync2(file);
    } catch {
    }
  }
  return null;
}

// src/statusline.ts
import { spawn } from "node:child_process";
var DEFAULT_TTL_SECONDS = 30;
var DEFAULT_GRACE_MINUTES = 15;
var COLD_FETCH_TIMEOUT_MS = 800;
var REFRESH_TIMEOUT_MS = 3e3;
var MAX_TEXT = 40;
var RENDER_FLAGS = /* @__PURE__ */ new Set(["--render", "--format", "--no-text", "--width", "--ttl", "--grace", "--refresh"]);
function isRenderInvocation(args) {
  return args.some((a) => RENDER_FLAGS.has(a.split("=")[0]));
}
function parseStatusArgs(args, env) {
  const opts = {
    format: "ansi",
    width: positiveInt(env.COLUMNS) ?? 0,
    ttlMs: DEFAULT_TTL_SECONDS * 1e3,
    graceMs: DEFAULT_GRACE_MINUTES * 6e4,
    showText: true,
    refresh: false
  };
  for (let i = 0; i < args.length; i++) {
    const [name, inline] = args[i].split(/=(.*)/s, 2);
    const value = () => inline ?? args[++i];
    switch (name) {
      case "--format": {
        const v = value();
        if (v === "ansi" || v === "tmux" || v === "plain") opts.format = v;
        break;
      }
      case "--width":
        opts.width = positiveInt(value()) ?? opts.width;
        break;
      case "--ttl":
        opts.ttlMs = (positiveInt(value()) ?? DEFAULT_TTL_SECONDS) * 1e3;
        break;
      case "--grace":
        opts.graceMs = (positiveInt(value()) ?? DEFAULT_GRACE_MINUTES) * 6e4;
        break;
      case "--no-text":
        opts.showText = false;
        break;
      case "--refresh":
        opts.refresh = true;
        break;
      default:
        break;
    }
  }
  return opts;
}
function positiveInt(raw) {
  if (raw === void 0 || !/^\d+$/.test(raw)) return void 0;
  const n = Number(raw);
  return n > 0 ? n : void 0;
}
var LOW_CREDITS = 20;
function cleanText(text, max = MAX_TEXT) {
  const flat = text.replace(/[\u0000-\u001f\u007f-\u009f]/g, " ").replace(/\s+/g, " ").trim();
  return flat.length > max ? `${flat.slice(0, max - 1)}\u2026` : flat;
}
function formatAge(ms) {
  const s = Math.max(0, Math.floor(ms / 1e3));
  if (s >= 86400) return `${Math.floor(s / 86400)}d`;
  if (s >= 3600) return `${Math.floor(s / 3600)}h`;
  if (s >= 60) return `${Math.floor(s / 60)}m`;
  return `${s}s`;
}
function formatWhen(at, now, timeZone) {
  const day = (d) => d.toLocaleDateString("en-CA", { timeZone });
  const time = at.toLocaleTimeString("en-GB", { timeZone, hour: "2-digit", minute: "2-digit", hour12: false });
  if (day(at) === day(now)) return time;
  const prefix = at.getTime() - now.getTime() < 6 * 864e5 ? at.toLocaleDateString("en-US", { timeZone, weekday: "short" }) : at.toLocaleDateString("en-US", { timeZone, month: "short", day: "numeric" });
  return `${prefix} ${time}`;
}
var dueTime = (r) => r.due_at ? Date.parse(r.due_at) : NaN;
function bodySegments(reminders, now, opts) {
  if (reminders.length === 0) return [];
  const t = now.getTime();
  const unseen = reminders.filter((r) => r.state === "due" || r.state === "scheduled" && dueTime(r) <= t);
  const tone = unseen.some((r) => t - dueTime(r) > opts.graceMs) ? "red" : unseen.length > 0 ? "yellow" : reminders.some((r) => r.state === "delivered") ? "dim" : "plain";
  const latest = [...reminders].sort((a, b) => Date.parse(b.created_at) - Date.parse(a.created_at) || b.position - a.position)[0];
  const more = reminders.length - 1;
  if (!opts.showText) return [{ text: `${reminders.length} open`, tone }];
  const when = latest.state === "scheduled" && dueTime(latest) > t ? ` @${formatWhen(new Date(dueTime(latest)), now, opts.timeZone)}` : "";
  return [{ text: `"${cleanText(latest.text)}"${when}${more > 0 ? ` +${more} more` : ""}`, tone }];
}
function renderStatus(input, now, opts) {
  let segments;
  if (input.kind === "logged_out") segments = [{ text: "mokkan: logged out", tone: "dim" }];
  else if (input.kind === "credentials_error") segments = [{ text: "mokkan: credentials error", tone: "dim" }];
  else if (input.kind === "unavailable") segments = [{ text: "mokkan: \u2026", tone: "dim" }];
  else segments = cacheSegments(input.cache, now, opts);
  return paint(truncate(segments, opts.width), opts.format);
}
function cacheSegments(cache, now, opts) {
  if (cache.error === "logged_out") return [{ text: "mokkan: logged out", tone: "dim" }];
  const body = bodySegments(cache.reminders, now, opts);
  const failed = cache.error !== null;
  if (failed && cache.fetched_at === null) return [{ text: cache.error === "offline" ? "mokkan: offline" : "mokkan: error", tone: "dim" }];
  const head = failed ? [{ text: `mokkan: ${cache.error === "offline" ? "offline" : "error"} (${formatAge(now.getTime() - Date.parse(cache.fetched_at))} old) \xB7 `, tone: "dim" }] : [{ text: "mokkan: ", tone: "plain" }];
  const credits = failed ? [] : creditSegments(cache.credit_balance);
  if (body.length === 0) return failed ? [...head, { text: "\u2713", tone: "green" }] : [{ text: "mokkan \u2713", tone: "green" }, ...credits];
  return [...head, ...body, ...credits];
}
function creditSegments(balance) {
  if (typeof balance !== "number" || !Number.isFinite(balance)) return [];
  if (balance >= LOW_CREDITS) return [{ text: ` \xB7 ${balance} cr`, tone: "dim", keep: true }];
  return [{ text: ` \xB7 \u26A0 ${balance} cr \u2014 mokkan buy`, tone: balance <= 0 ? "red" : "yellow", keep: true }];
}
function truncate(segments, width) {
  if (width <= 0) return segments;
  const len = (list) => list.reduce((n, s) => n + [...s.text].length, 0);
  if (len(segments) <= width) return segments;
  const kept = segments.filter((s) => s.keep === true);
  const reserved = len(kept);
  if (kept.length > 0 && reserved < width) {
    return [...cut(segments.filter((s) => s.keep !== true), width - reserved), ...kept];
  }
  return cut(segments, width);
}
function cut(segments, width) {
  const out = [];
  let left = width;
  for (const s of segments) {
    const chars = [...s.text];
    if (chars.length <= left) {
      out.push(s);
      left -= chars.length;
      continue;
    }
    if (left > 0) out.push({ text: `${chars.slice(0, left - 1).join("")}\u2026`, tone: s.tone });
    break;
  }
  return out;
}
var ANSI = {
  red: ["\x1B[31m", "\x1B[0m"],
  yellow: ["\x1B[33m", "\x1B[0m"],
  green: ["\x1B[32m", "\x1B[0m"],
  dim: ["\x1B[2m", "\x1B[0m"],
  plain: ["", ""]
};
var TMUX = {
  red: ["#[fg=red]", "#[fg=default]"],
  yellow: ["#[fg=yellow]", "#[fg=default]"],
  green: ["#[fg=green]", "#[fg=default]"],
  dim: ["#[dim]", "#[nodim]"],
  plain: ["", ""]
};
function paint(segments, format) {
  return segments.map(({ text, tone }) => {
    if (format === "plain") return text;
    if (format === "tmux") return `${TMUX[tone][0]}${text.replace(/#/g, "##")}${TMUX[tone][1]}`;
    return `${ANSI[tone][0]}${text}${ANSI[tone][1]}`;
  }).join("");
}
function slim(reminders) {
  return reminders.filter((r) => r.state !== "done").map(({ id, text, state, position, due_at, created_at }) => ({ id, text, state, position, due_at, created_at }));
}
function classify(err) {
  if (err instanceof NetworkError) return "offline";
  if (err instanceof SessionExpiredError || err instanceof ApiError && err.code === "no_credentials") return "logged_out";
  return "error";
}
async function refreshStatus(io, creds, makeClient2, timeoutMs) {
  const base = { v: 2, server_url: resolveServerUrl(creds, io.env), email: creds.email, attempted_at: io.now().toISOString() };
  let cache;
  try {
    const client = makeClient2(creds, timeoutMs);
    const [list, me] = await Promise.all([client.list("all"), client.me().catch(() => null)]);
    cache = { ...base, fetched_at: base.attempted_at, error: null, reminders: slim(list.reminders) };
    if (typeof me?.credit_balance === "number") {
      cache.credit_balance = me.credit_balance;
    } else if (me === null) {
      const prev = readStatusCache(io.env);
      if (prev && prev.server_url === base.server_url && prev.email === base.email && prev.credit_balance !== void 0) {
        cache.credit_balance = prev.credit_balance;
      }
    }
  } catch (err) {
    const prev = readStatusCache(io.env);
    const same = prev && prev.server_url === base.server_url && prev.email === base.email;
    cache = { ...base, fetched_at: same ? prev.fetched_at : null, error: classify(err), reminders: same ? prev.reminders : [] };
    if (same && prev.credit_balance !== void 0) cache.credit_balance = prev.credit_balance;
  }
  writeStatusCache(cache, io.env);
  return cache;
}
function spawnDetachedRefresh() {
  const child = spawn(process.execPath, [...process.execArgv, process.argv[1], "statusline", "--render", "--refresh"], {
    detached: true,
    stdio: "ignore"
  });
  child.on("error", () => void 0);
  child.unref();
}
async function statuslineCommand(io, args, makeClient2) {
  const opts = parseStatusArgs(args, io.env);
  const now = io.now();
  const print = (input) => {
    io.stdout(`${renderStatus(input, now, opts)}
`);
    return 0;
  };
  try {
    let creds;
    try {
      creds = loadCredentials(io.env);
    } catch {
      return opts.refresh ? 0 : print({ kind: "credentials_error" });
    }
    if (opts.refresh) {
      if (!creds) return 0;
      const release = tryAcquireRefreshLock(io.env);
      if (!release) return 0;
      try {
        await refreshStatus(io, creds, makeClient2, REFRESH_TIMEOUT_MS);
      } finally {
        release();
      }
      return 0;
    }
    if (!creds) return print({ kind: "logged_out" });
    let cache = readStatusCache(io.env);
    if (cache && (cache.server_url !== resolveServerUrl(creds, io.env) || cache.email !== creds.email)) cache = null;
    if (!cache) {
      cache = await refreshStatus(io, creds, makeClient2, COLD_FETCH_TIMEOUT_MS);
    } else if (now.getTime() - Date.parse(cache.attempted_at) >= opts.ttlMs && !refreshInFlight(io.env)) {
      (io.spawnRefresh ?? spawnDetachedRefresh)();
    }
    return print({ kind: "cache", cache });
  } catch {
    return opts.refresh ? 0 : print({ kind: "unavailable" });
  }
}

// src/statusline-setup.ts
import {
  accessSync,
  chmodSync as chmodSync3,
  constants,
  copyFileSync,
  existsSync as existsSync2,
  mkdirSync as mkdirSync4,
  readFileSync as readFileSync4,
  realpathSync,
  renameSync as renameSync3,
  statSync as statSync3,
  unlinkSync as unlinkSync3,
  writeFileSync as writeFileSync4
} from "node:fs";
import { randomBytes as randomBytes3 } from "node:crypto";
import { homedir as homedir2 } from "node:os";
import path4 from "node:path";
var TMUX_BEGIN = "# >>> mokkan status line >>>";
var TMUX_END = "# <<< mokkan status line <<<";
var REFRESH_INTERVAL_SECONDS = 30;
var SETUP_FLAGS = /* @__PURE__ */ new Set(["--claude", "--tmux", "--codex", "--remove", "--dry-run", "--force"]);
var SETUP_USAGE = "Usage: mokkan statusline [--claude] [--tmux|--codex] [--remove] [--dry-run] [--force]\n       mokkan statusline --render [--format ansi|tmux|plain] [--no-text] [--width N] [--ttl S] [--grace M]\n";
function parseSetupArgs(args) {
  const opts = { claude: false, tmux: false, auto: false, remove: false, dryRun: false, force: false, fromClaude: false };
  for (const arg of args) {
    if (!SETUP_FLAGS.has(arg)) return null;
    if (arg === "--claude") opts.claude = true;
    if (arg === "--tmux" || arg === "--codex") opts.tmux = true;
    if (arg === "--remove") opts.remove = true;
    if (arg === "--dry-run") opts.dryRun = true;
    if (arg === "--force") opts.force = true;
  }
  if (!opts.claude && !opts.tmux) {
    opts.claude = true;
    opts.tmux = true;
    opts.auto = true;
  }
  return opts;
}
function home(env) {
  return env.HOME && env.HOME !== "" ? env.HOME : homedir2();
}
function claudeConfigDir(env) {
  return env.CLAUDE_CONFIG_DIR && env.CLAUDE_CONFIG_DIR !== "" ? env.CLAUDE_CONFIG_DIR : path4.join(home(env), ".claude");
}
function claudeSettingsPath(env) {
  return path4.join(claudeConfigDir(env), "settings.json");
}
function tmuxConfPath(env) {
  const classic = path4.join(home(env), ".tmux.conf");
  const xdgBase = env.XDG_CONFIG_HOME && env.XDG_CONFIG_HOME !== "" ? env.XDG_CONFIG_HOME : path4.join(home(env), ".config");
  const xdg = path4.join(xdgBase, "tmux", "tmux.conf");
  return !existsSync2(classic) && existsSync2(xdg) ? xdg : classic;
}
function stableCliPath(env) {
  const base = env.XDG_DATA_HOME && env.XDG_DATA_HOME !== "" ? env.XDG_DATA_HOME : path4.join(home(env), ".local", "share");
  return path4.join(base, "mokkan", "mokkan.mjs");
}
function pluginCacheDirs(env) {
  const dirs = [path4.join(claudeConfigDir(env), "plugins", "cache"), path4.join(home(env), ".claude", "plugins", "cache")];
  const out = /* @__PURE__ */ new Set();
  for (const dir of dirs) {
    out.add(dir);
    try {
      out.add(realpathSync(dir));
    } catch {
    }
  }
  return [...out];
}
var isInside = (file, dir) => {
  const rel = path4.relative(dir, file);
  return rel !== "" && !rel.startsWith("..") && !path4.isAbsolute(rel);
};
function inPluginCache(file, env) {
  return pluginCacheDirs(env).some((dir) => isInside(file, dir));
}
function sameContent(a, b) {
  try {
    const sa = statSync3(a);
    const sb = statSync3(b);
    if (sa.size !== sb.size) return false;
    return readFileSync4(a).equals(readFileSync4(b));
  } catch {
    return false;
  }
}
function installCopy(source, target) {
  if (sameContent(source, target)) return false;
  mkdirSync4(path4.dirname(target), { recursive: true });
  const tmp = `${target}.${process.pid}.${randomBytes3(4).toString("hex")}.tmp`;
  try {
    copyFileSync(source, tmp);
    chmodSync3(tmp, 493);
    renameSync3(tmp, target);
  } catch (err) {
    try {
      unlinkSync3(tmp);
    } catch {
    }
    throw err;
  }
  return true;
}
var NpxCliError = class extends Error {
  constructor(file) {
    super(`mokkan is running from npx's temporary cache (${file}), which npm may delete at any time, so a status line must not point there. Run /mokkan:mokkan statusline in Claude Code (with the mokkan plugin), or npm i -g mokkan first and then mokkan statusline.`);
  }
};
function resolveCliLocation(running, env, write) {
  const real = realpathSync(running);
  if (real.split(path4.sep).includes("_npx")) throw new NpxCliError(real);
  if (!inPluginCache(real, env)) return { cli: real, copied: false };
  const target = stableCliPath(env);
  if (write) installCopy(real, target);
  return { cli: target, copied: true };
}
function refreshStableCopy(running, env) {
  const real = realpathSync(running);
  const target = stableCliPath(env);
  if (!inPluginCache(real, env) || !existsSync2(target)) return false;
  return installCopy(real, target);
}
function onPath(name, env) {
  for (const dir of (env.PATH ?? "").split(path4.delimiter)) {
    if (dir === "") continue;
    const file = path4.join(dir, name);
    try {
      accessSync(file, constants.X_OK);
      return file;
    } catch {
    }
  }
  return null;
}
function nodeWord(node, env) {
  try {
    const found = onPath("node", env);
    if (found !== null && realpathSync(found) === realpathSync(node)) return "node";
  } catch {
  }
  return node;
}
function shellWord(word) {
  return /^[\w@%+=:,./-]+$/.test(word) ? word : `'${word.replace(/'/g, `'\\''`)}'`;
}
function claudeCommand(node, cli) {
  return `${shellWord(node)} ${shellWord(cli)} statusline --render`;
}
function tmuxWord(word) {
  if (/[#'"$`\\\n]/.test(word)) throw new Error(`cannot use ${word} in a tmux status line (it contains # ' " $ \` or \\)`);
  return /^[\w@%+=:,./-]+$/.test(word) ? word : `"${word}"`;
}
function tmuxBlock(node, cli) {
  return [
    TMUX_BEGIN,
    "# Added by `mokkan statusline`; `mokkan statusline --remove --tmux` takes it out again.",
    "set -g status-interval 15",
    "set -g status-right-length 120",
    `set -g status-right '${tmuxSnippet(node, cli)} %H:%M'`,
    TMUX_END
  ].join("\n");
}
function shellWords(command) {
  const words = [];
  let cur = "";
  let started = false;
  for (let i = 0; i < command.length; i++) {
    const c = command[i];
    if (c === "'") {
      const end = command.indexOf("'", i + 1);
      if (end === -1) return null;
      cur += command.slice(i + 1, end);
      started = true;
      i = end;
    } else if (c === '"') {
      const end = command.indexOf('"', i + 1);
      if (end === -1) return null;
      const inner = command.slice(i + 1, end);
      if (/[$`\\]/.test(inner)) return null;
      cur += inner;
      started = true;
      i = end;
    } else if (/\s/.test(c)) {
      if (started) {
        words.push(cur);
        cur = "";
        started = false;
      }
    } else if (/[;&|<>()$`\\*?{}~#]/.test(c)) {
      return null;
    } else {
      cur += c;
      started = true;
    }
  }
  if (started) words.push(cur);
  return words;
}
var RENDER_WORDS = /^--(render|format|no-text|width|ttl|grace)(=.*)?$|^(ansi|tmux|plain|\d+)$/;
function isMokkanCommand(command) {
  const words = shellWords(command);
  if (!words) return false;
  const at = words.indexOf("statusline");
  if (at < 1 || at > 2) return false;
  const cli = words[at - 1];
  const base = path4.basename(cli);
  const cliLooksRight = base === "mokkan" || base === "mokkan.mjs" || /^cli\.m?js$/.test(base) && cli.includes("mokkan");
  if (!cliLooksRight) return false;
  if (at === 2 && !/^node(js)?(\d+)?(\.exe)?$/.test(path4.basename(words[0]))) return false;
  return words.slice(at + 1).every((w) => RENDER_WORDS.test(w));
}
function timestamp(now) {
  return now.toISOString().replace(/\.\d+Z$/, "Z").replace(/[-:]/g, "");
}
function backup(file, now) {
  const base = `${file}.mokkan-bak-${timestamp(now)}`;
  for (let n = 0; ; n++) {
    const target = n === 0 ? base : `${base}-${n}`;
    try {
      copyFileSync(file, target, constants.COPYFILE_EXCL);
      return target;
    } catch (err) {
      if (err.code !== "EEXIST") throw err;
    }
  }
}
function replaceFile(file, content, was, now) {
  let target = file;
  try {
    target = realpathSync(file);
  } catch {
  }
  let mode = 420;
  try {
    mode = statSync3(target).mode & 511;
  } catch {
  }
  mkdirSync4(path4.dirname(target), { recursive: true });
  const tmp = `${target}.${process.pid}.${randomBytes3(4).toString("hex")}.tmp`;
  let bak = null;
  try {
    writeFileSync4(tmp, content, { mode });
    chmodSync3(tmp, mode);
    const current = existsSync2(file) ? readFileSync4(file, "utf8") : null;
    if (current !== was) throw new Error(`${file} changed while mokkan was editing it; run the command again`);
    if (was !== null) bak = backup(file, now);
    renameSync3(tmp, target);
  } catch (err) {
    try {
      unlinkSync3(tmp);
    } catch {
    }
    if (bak !== null) {
      try {
        unlinkSync3(bak);
      } catch {
      }
    }
    throw err;
  }
  return bak;
}
function detectIndent(text) {
  const m = /^[ \t]*[{[][^\n]*\n([ \t]+)\S/.exec(text);
  return m ? m[1] : 2;
}
function readSettings(file) {
  if (!existsSync2(file)) return { settings: {}, text: null };
  const text = readFileSync4(file, "utf8");
  if (text.trim() === "") return { settings: {}, text };
  let value;
  try {
    value = JSON.parse(text);
  } catch {
    return { error: `${file} is not valid JSON; fix it first (nothing was changed)` };
  }
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return { error: `${file} does not hold a JSON object; fix it first (nothing was changed)` };
  }
  return { settings: value, text };
}
function statusLineCommandOf(value) {
  if (typeof value !== "object" || value === null) return void 0;
  const cmd = value.command;
  return typeof cmd === "string" ? cmd : void 0;
}
function writeSettings(file, settings, text, now) {
  const indent = text !== null ? detectIndent(text) : 2;
  return replaceFile(file, `${JSON.stringify(settings, null, indent)}
`, text, now);
}
function configureClaude(s, opts) {
  const file = claudeSettingsPath(s.env);
  const read = readSettings(file);
  if ("error" in read) return { lines: [`Claude Code: ${read.error}.`], failed: true, changed: false };
  const { settings, text } = read;
  const current = settings.statusLine;
  const currentCmd = statusLineCommandOf(current);
  const ours = currentCmd !== void 0 && isMokkanCommand(currentCmd);
  const command = claudeCommand(s.node, s.cli);
  if (opts.remove) {
    if (current === void 0) return { lines: [`Claude Code: no status line in ${file}; nothing to remove.`], failed: false, changed: false };
    if (!ours) {
      return { lines: [`Claude Code: the status line in ${file} is not mokkan's (${describe(current)}); left alone.`], failed: false, changed: false };
    }
    const next = { ...settings };
    delete next.statusLine;
    if (opts.dryRun) return { lines: [`Claude Code: would remove the mokkan status line from ${file}.`], failed: false, changed: true };
    const bak2 = writeSettings(file, next, text, s.now);
    return { lines: [`Claude Code: removed the mokkan status line from ${file}${bak2 ? ` (backup: ${bak2})` : ""}.`], failed: false, changed: true };
  }
  if (current !== void 0 && !ours && !opts.force) {
    const lines = [
      `Claude Code: ${file} already has a status line that is not mokkan's; left alone:`,
      `  ${describe(current)}`
    ];
    if (currentCmd?.includes("statusline") && currentCmd.includes("mokkan") && !currentCmd.includes("--render")) {
      lines.push("  It seems to call mokkan: change `statusline` to `statusline --render` there (the plain command now configures).");
    } else {
      lines.push(`  To show both, make your script also print the output of: ${command}`);
    }
    lines.push("  Or replace it: mokkan statusline --claude --force");
    return { lines, failed: true, changed: false };
  }
  const prev = typeof current === "object" && current !== null && ours ? current : {};
  const interval = typeof prev.refreshInterval === "number" ? prev.refreshInterval : REFRESH_INTERVAL_SECONDS;
  const wanted = { ...prev, type: "command", command, refreshInterval: interval };
  if (ours && JSON.stringify(current) === JSON.stringify(wanted)) {
    return { lines: [`Claude Code: already configured in ${file}.`], failed: false, changed: false };
  }
  const verb = current === void 0 ? "add" : ours ? "update" : "replace";
  const detail = `  "statusLine": ${JSON.stringify(wanted)}`;
  const was = current !== void 0 ? [`  (was: ${describe(current)})`] : [];
  if (opts.dryRun) {
    return { lines: [`Claude Code: would ${verb} the status line in ${file}:`, detail, ...was], failed: false, changed: true };
  }
  const bak = writeSettings(file, { ...settings, statusLine: wanted }, text, s.now);
  const done = { add: "added", update: "updated", replace: "replaced" }[verb];
  return {
    lines: [`Claude Code: ${done} the status line in ${file}${bak ? ` (backup: ${bak})` : ""}:`, detail, ...was],
    failed: false,
    changed: true
  };
}
function describe(value) {
  const cmd = statusLineCommandOf(value);
  return cmd !== void 0 ? cmd : JSON.stringify(value);
}
function findBlock(lines) {
  const trimmed = lines.map((l) => l.trimEnd());
  const start = trimmed.indexOf(TMUX_BEGIN);
  const end = trimmed.indexOf(TMUX_END);
  if (start === -1 && end === -1) return null;
  if (start === -1 || end === -1 || end < start) return "broken";
  if (trimmed.indexOf(TMUX_BEGIN, start + 1) !== -1) return "broken";
  return { start, end };
}
function configureTmux(s, opts) {
  const file = tmuxConfPath(s.env);
  const text = existsSync2(file) ? readFileSync4(file, "utf8") : null;
  const lines = text === null ? [] : text.replace(/\n$/, "").split("\n");
  if (text === "") lines.length = 0;
  const span = findBlock(lines);
  if (span === "broken") {
    return { lines: [`tmux: ${file} has an incomplete mokkan block (${TMUX_BEGIN} / ${TMUX_END}); fix it by hand (nothing was changed).`], failed: true, changed: false };
  }
  if (opts.remove) {
    if (!span) return { lines: [`tmux: no mokkan block in ${file}; nothing to remove.`], failed: false, changed: false };
    const next2 = [...lines.slice(0, span.start), ...lines.slice(span.end + 1)];
    const blank = (l) => l !== void 0 && l.trim() === "";
    if (span.start > 0 && blank(next2[span.start - 1]) && (span.start === next2.length || blank(next2[span.start]))) next2.splice(span.start - 1, 1);
    if (opts.dryRun) return { lines: [`tmux: would remove the mokkan block from ${file}.`], failed: false, changed: true };
    const bak2 = replaceFile(file, next2.length > 0 ? `${next2.join("\n")}
` : "", text, s.now);
    return { lines: [`tmux: removed the mokkan block from ${file} (backup: ${bak2}).`, ...reloadHint(file)], failed: false, changed: true };
  }
  let block;
  try {
    block = tmuxBlock(s.node, s.cli);
  } catch (err) {
    return { lines: [`tmux: ${err.message}; nothing was changed.`], failed: true, changed: false };
  }
  const blockLines = block.split("\n");
  if (!span && !opts.force) {
    const foreign = foreignTmuxConfig(lines);
    if (foreign) {
      const combine = [
        `  To show mokkan there too, add this to your status-right: ${tmuxSnippet(s.node, s.cli)}`,
        `  Or let mokkan's block override it: mokkan statusline --tmux --force`
      ];
      if (opts.auto) {
        return { lines: [`tmux: skipped: ${file} ${foreign}, which mokkan's block would override.`, ...combine], failed: false, changed: false };
      }
      return { lines: [`tmux: ${file} ${foreign}; left alone (nothing was changed).`, ...combine], failed: true, changed: false };
    }
  }
  let next;
  if (span) {
    if (lines.slice(span.start, span.end + 1).join("\n") === block) {
      return { lines: [`tmux: already configured in ${file}.`, ...foreignNotes(lines, span)], failed: false, changed: false };
    }
    next = [...lines.slice(0, span.start), ...blockLines, ...lines.slice(span.end + 1)];
  } else {
    next = lines.length > 0 && lines[lines.length - 1] !== "" ? [...lines, "", ...blockLines] : [...lines, ...blockLines];
  }
  const newSpan = findBlock(next);
  const notes = foreignNotes(next, newSpan);
  const verb = span ? "update" : "add";
  if (opts.dryRun) {
    return { lines: [`tmux: would ${verb} this block in ${file}:`, ...blockLines.map((l) => `  ${l}`), ...notes], failed: false, changed: true };
  }
  const bak = replaceFile(file, `${next.join("\n")}
`, text, s.now);
  return {
    lines: [`tmux: ${span ? "updated" : "added"} the mokkan block in ${file}${bak ? ` (backup: ${bak})` : ""}.`, ...notes, ...reloadHint(file)],
    failed: false,
    changed: true
  };
}
var STATUS_RIGHT = /^\s*set(-option)?\s+(-\w+\s+)*status-right\s/;
var TPM_RUN = /^\s*run(-shell)?\s.*\btpm\b/;
var isOlderMokkanLine = (line) => line.includes("mokkan") || line.includes("statusline");
function foreignTmuxConfig(lines) {
  const own = lines.findIndex((l) => STATUS_RIGHT.test(l) && !isOlderMokkanLine(l));
  if (own !== -1) return `sets its own status-right (line ${own + 1})`;
  const tpm = lines.findIndex((l) => TPM_RUN.test(l));
  if (tpm !== -1) return `loads tmux plugins through TPM (line ${tpm + 1}), whose themes set status-right`;
  return null;
}
function tmuxSnippet(node, cli) {
  return `#(${tmuxWord(node)} ${tmuxWord(cli)} statusline --render --format tmux)`;
}
function foreignNotes(lines, span) {
  const notes = [];
  lines.forEach((line, i) => {
    if (i >= span.start && i <= span.end) return;
    if (!STATUS_RIGHT.test(line)) return;
    if (i > span.end) {
      notes.push(`  note: line ${i + 1} sets status-right after the mokkan block, so it hides mokkan.`);
    } else if (isOlderMokkanLine(line)) {
      notes.push(`  note: line ${i + 1} is an older mokkan status-right (outside the block); the block overrides it, you can delete it.`);
    } else {
      notes.push(`  note: line ${i + 1} sets your own status-right; the mokkan block overrides it. To keep both, add #(...) from the block to yours and run mokkan statusline --remove --tmux.`);
    }
  });
  return notes;
}
function reloadHint(file) {
  return [`  If tmux is running, reload it: tmux source-file ${file}`];
}
function tmuxOnPath(env) {
  return onPath("tmux", env) !== null;
}
function removeUnusedStableCopy(env) {
  const stable = stableCliPath(env);
  if (!existsSync2(stable)) return [];
  for (const file of [claudeSettingsPath(env), tmuxConfPath(env)]) {
    try {
      if (readFileSync4(file, "utf8").includes(stable)) return [];
    } catch {
    }
  }
  try {
    unlinkSync3(stable);
    return [`CLI: removed the copy at ${stable}.`];
  } catch (err) {
    return [`CLI: could not remove ${stable}: ${err.message}`];
  }
}
function statuslineSetupCommand(io, args, deps, fromClaude = false) {
  const parsed = parseSetupArgs(args);
  if (!parsed) {
    io.stderr(SETUP_USAGE);
    return 1;
  }
  const opts = { ...parsed, fromClaude };
  const env = io.env;
  let location;
  try {
    location = resolveCliLocation(deps.running, env, !opts.dryRun && !opts.remove);
  } catch (err) {
    if (err instanceof NpxCliError && opts.remove) {
      location = { cli: deps.running, copied: false };
    } else {
      io.stderr(err instanceof NpxCliError ? `${err.message}
` : `Cannot find the running mokkan CLI (${deps.running}): ${err.message}
`);
      return 1;
    }
  }
  const s = { env, now: io.now(), node: nodeWord(deps.node, env), cli: location.cli };
  const out = [];
  let failed = false;
  let claudeChanged = false;
  let tmuxChanged = false;
  const run2 = (label, fn) => {
    try {
      const o = fn();
      out.push(...o.lines);
      failed ||= o.failed;
      return o;
    } catch (err) {
      out.push(`${label}: ${err.message}; nothing was changed.`);
      failed = true;
      return null;
    }
  };
  if (opts.claude) {
    if (opts.auto && !existsSync2(claudeConfigDir(env))) {
      out.push(`Claude Code: ${claudeConfigDir(env)} does not exist; skipped (use --claude to set it up anyway).`);
    } else {
      claudeChanged = run2("Claude Code", () => configureClaude(s, opts))?.changed === true;
    }
  }
  if (opts.tmux) {
    if (opts.auto && opts.fromClaude && !opts.remove) {
      out.push("tmux: not set up from Claude Code; add --tmux for the tmux block (Codex shows mokkan only inside tmux).");
    } else if (opts.auto && !tmuxOnPath(env)) {
      out.push("tmux: not installed; skipped (Codex shows mokkan only inside tmux; use --tmux to write the block anyway).");
    } else {
      tmuxChanged = run2("tmux", () => configureTmux(s, opts))?.changed === true;
      if (!opts.remove) out.push("  Codex: its own footer cannot run commands; run Codex inside tmux to see mokkan in the tmux status bar.");
    }
  }
  if (opts.remove && !opts.dryRun) out.push(...removeUnusedStableCopy(env));
  if (location.copied && !opts.remove) {
    out.push(opts.dryRun ? `CLI: would copy the plugin's CLI to ${location.cli} (the plugin path changes on every update).` : `CLI: the status line runs ${location.cli}, a copy of the plugin's CLI kept up to date by the plugin's SessionStart hook.`);
  }
  if (opts.dryRun) out.push("Dry run: nothing was written.");
  else if (claudeChanged) out.push("Restart Claude Code (or open a new session) to see the status line.");
  io.stdout(`${out.join("\n")}
`);
  return failed ? 1 : 0;
}
var MIGRATE_RETRY_MS = 24 * 60 * 60 * 1e3;
function migrateStampPath(env) {
  return path4.join(configDir(env), "statusline-migrate-failed");
}
function recentMigrateFailure(env, now) {
  try {
    const at = Date.parse(readFileSync4(migrateStampPath(env), "utf8").trim());
    return Number.isFinite(at) && now.getTime() - at < MIGRATE_RETRY_MS && now.getTime() >= at;
  } catch {
    return false;
  }
}
function stampMigrateFailure(env, now) {
  try {
    mkdirSync4(configDir(env), { recursive: true, mode: 448 });
    writeFileSync4(migrateStampPath(env), `${now.toISOString()}
`, { mode: 384 });
  } catch {
  }
}
function migrateLegacyInvocation(io, deps) {
  let cmd;
  try {
    const file = claudeSettingsPath(io.env);
    if (!existsSync2(file)) return false;
    const read = readSettings(file);
    if ("error" in read) return false;
    cmd = statusLineCommandOf(read.settings.statusLine);
  } catch {
    return false;
  }
  if (cmd === void 0 || !isMokkanCommand(cmd)) return false;
  if (/(^|\s)--render(\s|$)/.test(cmd)) return true;
  const now = io.now();
  if (recentMigrateFailure(io.env, now)) return true;
  try {
    const location = resolveCliLocation(deps.running, io.env, true);
    const outcome = configureClaude(
      { env: io.env, now, node: nodeWord(deps.node, io.env), cli: location.cli },
      { claude: true, tmux: false, auto: false, remove: false, dryRun: false, force: false, fromClaude: false }
    );
    if (outcome.failed) stampMigrateFailure(io.env, now);
    else {
      try {
        unlinkSync3(migrateStampPath(io.env));
      } catch {
      }
    }
  } catch {
    stampMigrateFailure(io.env, now);
  }
  return true;
}
function nonTerminalHint(env) {
  let text = "";
  try {
    text = readFileSync4(claudeSettingsPath(env), "utf8");
  } catch {
  }
  if (text.includes("statusline") && !text.includes("--render")) {
    return 'mokkan: run "mokkan statusline" in a terminal to update this status line';
  }
  return 'mokkan: nothing was set up without a terminal; run "mokkan statusline" in one, or "mokkan statusline --claude" (or --tmux) here';
}

// src/cli.ts
var BOOLEAN_FLAGS = /* @__PURE__ */ new Set(["json", "all", "once", "start", "complete", "help", "exit-zero"]);
var VALUE_FLAGS = /* @__PURE__ */ new Set(["otp", "source", "interval"]);
var COMMAND_FLAGS = /* @__PURE__ */ new Map([
  ["edit", { boolean: ["clear-due"], value: ["text", "in", "at"] }],
  ["buy", { boolean: ["no-open"], value: ["pack"] }]
]);
function parseArgs(argv) {
  if (argv[0] !== "--argline") return parseWords(argv);
  const words = (argv[1] ?? "").trim().split(/\s+/).filter((w) => w !== "");
  const user = parseWords(words);
  const fixed = parseWords(["_", ...argv.slice(2)]);
  return { command: user.command, args: user.args, flags: { ...user.flags, ...fixed.flags } };
}
function parseWords(argv) {
  const flags = {};
  const positional = [];
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--") {
      positional.push(...argv.slice(i + 1));
      break;
    }
    if (arg.startsWith("--")) {
      const eq = arg.indexOf("=");
      const name = eq === -1 ? arg.slice(2) : arg.slice(2, eq);
      const scoped = positional.length > 0 ? COMMAND_FLAGS.get(positional[0]) : void 0;
      const scopedValue = scoped?.value.includes(name) === true;
      if (VALUE_FLAGS.has(name) || scopedValue) {
        if (eq !== -1) {
          flags[name] = arg.slice(eq + 1);
        } else if (i + 1 < argv.length) {
          flags[name] = argv[i + 1];
          i++;
        } else if (scopedValue) {
          flags[name] = "";
        }
        continue;
      }
      if (eq === -1 && (BOOLEAN_FLAGS.has(name) || scoped?.boolean.includes(name) === true)) {
        flags[name] = true;
        continue;
      }
    }
    positional.push(arg);
  }
  return { command: positional[0], args: positional.slice(1), flags };
}
var USAGE = `Usage: mokkan <command> [args] [--json]

  mokkan [list] [--all]           active list, top of stack first (--all adds scheduled)
  mokkan push <text>              add to the top
  mokkan pop                      remove from the top (LIFO)
  mokkan dequeue                  remove from the bottom (FIFO)
  mokkan in <duration> <text>     schedule: 30s, 10m, 2h, 1d, 1h30m
  mokkan ack <id-prefix>... | all acknowledge shown reminders
  mokkan edit <n|id> [--all] [--in <duration> | --at <iso> | --clear-due] [new text...]
                                  change text and/or time of a reminder in one call; n = number in
                                  mokkan list (mokkan list --all with --all), or an id prefix
  mokkan pending                  due + awaiting acknowledgment
  mokkan done                     history of popped items
  mokkan status                   server, account, session state
  mokkan buy [--pack <key>] [--no-open]
                                  buy credits: prints (and opens) a Stripe Checkout link
  mokkan balance [--json]         credit balance and recent transactions
  mokkan register [email]         create an account (--start | --complete --otp <code>)
  mokkan login [email]            log in (password from prompt or MOKKAN_PASSWORD)
  mokkan logout
  mokkan heartbeat [--source X]   tell the server a session is active
  mokkan hook session-start|stop  Claude Code hook entrypoints (JSON on stdin)
  mokkan watch [--interval N]     foreground poller (--once for a single pass)
  mokkan statusline [--claude] [--tmux|--codex] [--remove] [--dry-run] [--force]
                                  set up the status line: Claude Code's settings.json, plus a marked block in
                                  ~/.tmux.conf when tmux is installed and has no status-right or TPM of its own
                                  (Codex shows it through tmux); backups first, never replaces a status line that
                                  is not mokkan's without --force; from /mokkan only Claude Code unless --tmux
  mokkan statusline --render [--format ansi|tmux|plain] [--no-text] [--width N] [--ttl S] [--grace M]
                                  print the one-line summary (what the status line runs; always exits 0)

  --exit-zero                     report errors on stdout and always exit 0 (for the /mokkan slash command)
  --argline "<words>"             first argument only: split the string on whitespace and use it as the arguments
`;
function sleep(ms, signal) {
  return new Promise((resolve) => {
    const timer = setTimeout(resolve, ms);
    signal?.addEventListener("abort", () => {
      clearTimeout(timer);
      resolve();
    }, { once: true });
  });
}
function defaultIO() {
  return {
    stdout: (text) => {
      process.stdout.write(text);
    },
    stderr: (text) => {
      process.stderr.write(text);
    },
    env: process.env,
    isTTY: Boolean(process.stdin.isTTY && process.stdout.isTTY),
    stdinIsTTY: Boolean(process.stdin.isTTY),
    prompt: promptLine,
    readStdin: readAllStdin,
    now: () => /* @__PURE__ */ new Date(),
    sleep,
    openUrl: openUrlDetached
  };
}
var EXIT_INSUFFICIENT_CREDITS = 3;
function reportError(err, io) {
  if (err instanceof UserError || err instanceof CredentialsPermissionError) {
    io.stderr(`${err.message}
`);
    return 1;
  }
  if (err instanceof ApiError) {
    io.stderr(`${err.message}
`);
    const body = err.body ?? {};
    if (err.status === 402 && typeof body.required === "number" && typeof body.cost === "number" && body.required > body.cost) {
      io.stderr(`(${body.required - body.cost} credits are kept for pending reminder emails; acknowledge shown reminders with \`mokkan ack\` or run \`mokkan buy\`)
`);
    }
    if (err.status === 429 && err.retryAfterSeconds !== void 0) {
      const s = Math.ceil(err.retryAfterSeconds);
      io.stderr(`(try again in about ${s >= 60 ? `${Math.ceil(s / 60)} minutes` : `${s} seconds`})
`);
    }
    if (err.status === 402 && err.code === "insufficient_credits") return EXIT_INSUFFICIENT_CREDITS;
    return err.status >= 500 ? 2 : 1;
  }
  if (err instanceof NetworkError || err instanceof CredentialsLockError) {
    io.stderr(`${err.message}
`);
    return 2;
  }
  io.stderr(`Unexpected error: ${err instanceof Error ? err.message : String(err)}
`);
  return 2;
}
function makeClient(creds, io, timeoutMs, signal) {
  return new MokkanClient({
    baseUrl: resolveServerUrl(creds, io.env),
    credentials: creds,
    onCredentials: (next) => saveCredentials(next, io.env),
    reloadCredentials: () => loadCredentials(io.env),
    lock: (fn, lockSignal) => withCredentialsLock(io.env, fn, { signal: lockSignal }),
    onSessionExpired: () => clearCredentials(io.env),
    onListChanged: () => invalidateStatusCache(io.env),
    fetchImpl: io.fetchImpl,
    now: io.now,
    timeoutMs,
    signal
  });
}
async function hookEntry(args, flags, io) {
  const kind = args[0];
  if (kind !== "session-start" && kind !== "stop") {
    io.stderr("Usage: mokkan hook session-start|stop\n");
    return 1;
  }
  if (kind === "session-start") {
    try {
      refreshStableCopy(setupDeps(io).running, io.env);
    } catch {
    }
  }
  try {
    const deadlineAt = Date.now() + HOOK_BUDGET_MS;
    const client = makeClient(loadCredentials(io.env), io, 3e3, AbortSignal.timeout(HOOK_BUDGET_MS));
    return await hookCommand({ io, client, json: flags.json === true, flags, now: io.now }, args, deadlineAt);
  } catch (err) {
    safeAppendHookLog(io.env, kind, err);
    return 0;
  }
}
function setupDeps(io) {
  return { running: io.cliPath ?? process.argv[1] ?? "", node: io.nodePath ?? process.execPath };
}
async function statuslineEntry(args, flags, io) {
  const render = () => statuslineCommand(io, args, (creds, timeoutMs) => makeClient(creds, io, timeoutMs));
  if (isRenderInvocation(args)) return render();
  const deps = setupDeps(io);
  const fromClaude = flags["exit-zero"] === true;
  if (args.length === 0 && !(io.stdinIsTTY ?? io.isTTY) && !fromClaude) {
    if (migrateLegacyInvocation(io, deps)) return render();
    io.stdout(`${nonTerminalHint(io.env)}
`);
    return 0;
  }
  return statuslineSetupCommand(io, args, deps, fromClaude);
}
async function main(argv, io) {
  const parsed = parseArgs(argv);
  if (parsed.flags["exit-zero"] !== true) return run(parsed, io);
  await run(parsed, { ...io, stderr: io.stdout });
  return 0;
}
async function run({ command, args, flags }, io) {
  if (command === "help" || flags.help === true) {
    io.stdout(USAGE);
    return 0;
  }
  if (command === "hook") return hookEntry(args, flags, io);
  if (command === "statusline") return statuslineEntry(args, flags, io);
  try {
    let creds;
    try {
      creds = loadCredentials(io.env);
    } catch (err) {
      if (!(err instanceof CredentialsCorruptError) || command !== "login" && command !== "logout") throw err;
      if (command === "logout") {
        clearCredentials(io.env);
        io.stdout(`Removed corrupt credentials file ${err.file}.
Logged out.
`);
        return 0;
      }
      creds = null;
    }
    const client = makeClient(creds, io, 5e3);
    const ctx = { io, client, json: flags.json === true, flags, now: io.now };
    switch (command) {
      case void 0:
      case "list":
        return await listCommand(ctx);
      case "done":
        return await doneCommand(ctx);
      case "pending":
        return await pendingCommand(ctx);
      case "push":
        return await pushCommand(ctx, args);
      case "pop":
        return await takeCommand(ctx, "pop");
      case "dequeue":
        return await takeCommand(ctx, "dequeue");
      case "in":
        return await inCommand(ctx, args);
      case "ack":
        return await ackCommand(ctx, args);
      case "edit":
        return await editCommand(ctx, args);
      case "register":
        return await registerCommand(ctx, args);
      case "login":
        return await loginCommand(ctx, args);
      case "logout":
        return await logoutCommand(ctx);
      case "status":
        return await statusCommand(ctx);
      case "buy":
        return await buyCommand(ctx);
      case "balance":
        return await balanceCommand(ctx);
      case "heartbeat":
        return await heartbeatCommand(ctx);
      case "watch":
        return await watchCommand(ctx);
      default:
        throw new UserError(`Unknown command "${command}".
${USAGE}`);
    }
  } catch (err) {
    return reportError(err, io);
  }
}
var invokedDirectly = process.argv[1] !== void 0 && import.meta.url === pathToFileURL(realpathSync2(process.argv[1])).href;
if (invokedDirectly) {
  process.exitCode = await main(process.argv.slice(2), defaultIO());
}
export {
  EXIT_INSUFFICIENT_CREDITS,
  USAGE,
  defaultIO,
  main,
  parseArgs,
  sleep
};
