#!/usr/bin/env node
// Generated by `npm run bundle` from src/ (tools/bundle.mjs). Do not edit; change src/ and rebuild.

// src/cli.ts
import { realpathSync as realpathSync2 } from "node:fs";
import { pathToFileURL } from "node:url";

// src/errors.ts
var UserError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "UserError";
  }
};
var SessionExpiredError = class extends UserError {
  constructor() {
    super("Session expired on this machine; run: mokkan login");
    this.name = "SessionExpiredError";
  }
};

// src/client.ts
var ApiError = class extends Error {
  constructor(status2, code, message, body, retryAfterSeconds) {
    super(message);
    this.status = status2;
    this.code = code;
    this.body = body;
    this.retryAfterSeconds = retryAfterSeconds;
    this.name = "ApiError";
  }
  status;
  code;
  body;
  retryAfterSeconds;
};
function apiErrorHint(err) {
  const body = err.body ?? {};
  if (err.status === 402 && typeof body.required === "number" && typeof body.cost === "number" && body.required > body.cost) {
    return `(${body.required - body.cost} credits are kept for pending reminder emails; acknowledge shown reminders with \`mokkan ack\` or run \`mokkan buy\`)`;
  }
  if (err.status === 429 && err.retryAfterSeconds !== void 0) {
    const s = Math.ceil(err.retryAfterSeconds);
    return `(try again in about ${s >= 60 ? `${Math.ceil(s / 60)} minutes` : `${s} seconds`})`;
  }
  return null;
}
var NetworkError = class extends Error {
  constructor(message, cause) {
    super(message);
    this.cause = cause;
    this.name = "NetworkError";
  }
  cause;
};
var REFRESH_AHEAD_MS = 3600 * 1e3;
var CHECKOUT_TIMEOUT_MS = 3e4;
var MokkanClient = class {
  baseUrl;
  credentials;
  onCredentials;
  reloadCredentials;
  lock;
  onSessionExpired;
  onListChanged;
  fetchImpl;
  timeoutMs;
  signal;
  now;
  /** The in-flight refresh, shared by every caller: the server rotates refresh tokens and treats reuse as theft. */
  refreshing = null;
  constructor(opts) {
    this.baseUrl = opts.baseUrl.replace(/\/+$/, "");
    this.credentials = opts.credentials ?? null;
    this.onCredentials = opts.onCredentials;
    this.reloadCredentials = opts.reloadCredentials;
    this.lock = opts.lock ?? ((fn) => fn());
    this.onSessionExpired = opts.onSessionExpired;
    this.onListChanged = opts.onListChanged ?? (() => void 0);
    this.fetchImpl = opts.fetchImpl ?? fetch;
    this.timeoutMs = opts.timeoutMs ?? 5e3;
    this.signal = opts.signal;
    this.now = opts.now ?? (() => /* @__PURE__ */ new Date());
  }
  hasCredentials() {
    return this.credentials !== null;
  }
  get email() {
    return this.credentials?.email ?? null;
  }
  // ---- unauthenticated ----
  health() {
    return this.call("GET", "/health");
  }
  async registerStart(email) {
    await this.call("POST", "/auth/register/start", { email });
  }
  async registerComplete(email, otp, password) {
    const pair = await this.call("POST", "/auth/register/complete", { email, otp, password });
    this.onListChanged();
    return this.adopt(pair, email);
  }
  async login(email, password) {
    const pair = await this.call("POST", "/auth/login", { email, password });
    this.onListChanged();
    return this.adopt(pair, email);
  }
  /** Single-flight: concurrent callers share one /auth/refresh request instead of each rotating the same token. */
  refresh() {
    if (this.refreshing) return this.refreshing;
    const inFlight = this.refreshOnce().finally(() => {
      if (this.refreshing === inFlight) this.refreshing = null;
    });
    this.refreshing = inFlight;
    return inFlight;
  }
  /**
   * Cross-process safe rotation. The server revokes the whole token family when a refresh token is presented twice,
   * so before refreshing we re-read the credentials file: if another process already rotated, adopt its tokens.
   * The re-read, the refresh and the save run under an exclusive lock file so two processes can never both
   * present the same refresh token.
   */
  async refreshOnce() {
    const current = this.credentials;
    if (!current) throw new ApiError(401, "no_credentials", "Not logged in. Run: mokkan login");
    const rotatedElsewhere = () => {
      const stored = this.reloadCredentials?.() ?? null;
      return stored && stored.refresh_token !== current.refresh_token ? stored : null;
    };
    const early = rotatedElsewhere();
    if (early) return this.adoptStored(early);
    try {
      return await this.lock(async () => {
        const stored = rotatedElsewhere();
        if (stored) return this.adoptStored(stored);
        let pair;
        try {
          pair = await this.call("POST", "/auth/refresh", { refresh_token: current.refresh_token });
        } catch (err) {
          if (err instanceof ApiError && err.status === 401 && err.code === "invalid_token") {
            this.credentials = null;
            this.onSessionExpired?.();
            throw new SessionExpiredError();
          }
          throw err;
        }
        return this.adopt(pair, current.email);
      }, this.signal);
    } catch (err) {
      if (err instanceof SessionExpiredError) throw err;
      let stored = null;
      try {
        stored = rotatedElsewhere();
      } catch {
      }
      if (stored) return this.adoptStored(stored);
      throw err;
    }
  }
  /** Tokens another process already saved: use them without saving again. */
  adoptStored(stored) {
    this.credentials = stored;
    return stored;
  }
  // ---- authenticated ----
  async logout() {
    await this.authed("POST", "/auth/logout");
    this.credentials = null;
    this.onListChanged();
  }
  me() {
    return this.authed("GET", "/me");
  }
  heartbeat(source, sessionId) {
    return this.authed("POST", "/heartbeat", sessionId === void 0 ? { source } : { source, session_id: sessionId });
  }
  list(scope = "active") {
    return this.authed("GET", `/reminders?scope=${scope}`);
  }
  push(text, dueAt, clientId) {
    const body = { text };
    if (dueAt) body.due_at = dueAt.toISOString();
    if (clientId !== void 0) body.client_id = clientId;
    return this.changing(this.authed("POST", "/reminders", body));
  }
  /** Changes text and/or due_at (null clears it). Every 3rd successful edit costs a credit. */
  editReminder(id, patch, expectedVersion) {
    const body = {};
    if (patch.text !== void 0) body.text = patch.text;
    if (patch.due_at !== void 0) body.due_at = patch.due_at === null ? null : patch.due_at.toISOString();
    if (expectedVersion !== void 0) body.expected_version = expectedVersion;
    return this.changing(this.authed("PATCH", `/reminders/${encodeURIComponent(id)}`, body));
  }
  /** Starts a Stripe Checkout session for a credit pack (default pack when omitted). */
  checkout(pack) {
    return this.authed("POST", "/billing/checkout", pack === void 0 ? {} : { pack }, CHECKOUT_TIMEOUT_MS);
  }
  balance() {
    return this.authed("GET", "/billing/balance");
  }
  pop(expectedVersion) {
    return this.changing(this.authed("POST", "/reminders/pop", expectedVersion === void 0 ? {} : { expected_version: expectedVersion }));
  }
  dequeue(expectedVersion) {
    return this.changing(this.authed("POST", "/reminders/dequeue", expectedVersion === void 0 ? {} : { expected_version: expectedVersion }));
  }
  pending() {
    return this.authed("GET", "/reminders/pending");
  }
  deliver(ids) {
    return this.changing(this.authed("POST", "/reminders/deliver", { ids }));
  }
  /** `done: true` finishes one reminder as pop does; `false` reopens a done one at its old position. Free. */
  setDone(id, done, expectedVersion) {
    const body = { done };
    if (expectedVersion !== void 0) body.expected_version = expectedVersion;
    return this.changing(this.authed("POST", `/reminders/${encodeURIComponent(id)}/done`, body));
  }
  ack(idsOrAll, expectedVersion) {
    const body = idsOrAll === "all" ? { all: true } : { ids: idsOrAll };
    if (expectedVersion !== void 0) body.expected_version = expectedVersion;
    return this.changing(this.authed("POST", "/reminders/ack", body));
  }
  // ---- internals ----
  async changing(request) {
    const result = await request;
    this.onListChanged();
    return result;
  }
  adopt(pair, email) {
    this.credentials = {
      server_url: this.baseUrl,
      email,
      access_token: pair.access_token,
      access_expires_at: pair.access_expires_at,
      refresh_token: pair.refresh_token,
      refresh_expires_at: pair.refresh_expires_at
    };
    this.onCredentials?.(this.credentials);
    return this.credentials;
  }
  async call(method, path4, body) {
    const res = await this.raw(method, path4, body);
    if (res.status >= 400) throw toApiError(res);
    return res.json;
  }
  async authed(method, path4, body, timeoutMs) {
    if (!this.credentials) throw new ApiError(401, "no_credentials", "Not logged in. Run: mokkan login");
    const expiresAt = Date.parse(this.credentials.access_expires_at);
    if (Number.isFinite(expiresAt) && expiresAt - this.now().getTime() < REFRESH_AHEAD_MS) {
      await this.refresh();
    }
    const sentToken = this.credentials.access_token;
    let res = await this.raw(method, path4, body, sentToken, timeoutMs);
    if (res.status === 401) {
      if (this.refreshing || this.credentials?.access_token === sentToken) await this.refresh();
      if (!this.credentials) throw toApiError(res);
      res = await this.raw(method, path4, body, this.credentials.access_token, timeoutMs);
    }
    if (res.status >= 400) throw toApiError(res);
    return res.json;
  }
  async raw(method, path4, body, token, timeoutMs = this.timeoutMs) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);
    const headers = { accept: "application/json" };
    if (body !== void 0) headers["content-type"] = "application/json";
    if (token) headers.authorization = `Bearer ${token}`;
    try {
      const res = await this.fetchImpl(`${this.baseUrl}${path4}`, {
        method,
        headers,
        body: body === void 0 ? void 0 : JSON.stringify(body),
        signal: this.signal ? AbortSignal.any([controller.signal, this.signal]) : controller.signal
      });
      const text = await res.text();
      let json = null;
      if (text !== "") {
        try {
          json = JSON.parse(text);
        } catch {
          json = { error: "bad_response", message: text.slice(0, 200) };
        }
      }
      const ra = Number(res.headers?.get("retry-after"));
      return { status: res.status, json, retryAfterSeconds: Number.isFinite(ra) && ra > 0 ? ra : void 0 };
    } catch (err) {
      const reason = controller.signal.aborted ? `timed out after ${timeoutMs} ms` : this.signal?.aborted ? "overall deadline exceeded" : err.message;
      throw new NetworkError(`Cannot reach ${this.baseUrl}: ${reason}`, err);
    } finally {
      clearTimeout(timer);
    }
  }
};
function toApiError(res) {
  const body = res.json ?? {};
  const code = typeof body.error === "string" ? body.error : "error";
  const message = typeof body.message === "string" ? body.message : `HTTP ${res.status}`;
  return new ApiError(res.status, code, message, res.json, res.retryAfterSeconds);
}

// src/credentials.ts
import {
  chmodSync,
  closeSync,
  existsSync,
  mkdirSync,
  openSync,
  readFileSync,
  renameSync,
  statSync,
  unlinkSync,
  writeFileSync,
  writeSync
} from "node:fs";
import { randomBytes } from "node:crypto";
import { homedir } from "node:os";
import path from "node:path";
var DEFAULT_SERVER_URL = "https://api.mokkan.dev";
var CredentialsPermissionError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "CredentialsPermissionError";
  }
};
var CredentialsCorruptError = class extends UserError {
  constructor(file) {
    super(`credentials file is corrupt: ${file}. Run: mokkan logout (or delete it) then mokkan login`);
    this.file = file;
    this.name = "CredentialsCorruptError";
  }
  file;
};
var REQUIRED_KEYS = ["server_url", "email", "access_token", "access_expires_at", "refresh_token", "refresh_expires_at"];
function configDir(env = process.env) {
  const base = env.XDG_CONFIG_HOME && env.XDG_CONFIG_HOME !== "" ? env.XDG_CONFIG_HOME : path.join(env.HOME && env.HOME !== "" ? env.HOME : homedir(), ".config");
  return path.join(base, "mokkan");
}
function credentialsPath(env = process.env) {
  return path.join(configDir(env), "credentials.json");
}
function credentialsLockPath(env = process.env) {
  return `${credentialsPath(env)}.lock`;
}
function hookLogPath(env = process.env) {
  return path.join(configDir(env), "hook.log");
}
function loadCredentials(env = process.env) {
  const file = credentialsPath(env);
  if (!existsSync(file)) return null;
  const mode = statSync(file).mode & 511;
  if (mode & 63) {
    throw new CredentialsPermissionError(`${file} is readable by other users (mode ${mode.toString(8)}). Fix with: chmod 600 ${file}`);
  }
  const text = readFileSync(file, "utf8");
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new CredentialsCorruptError(file);
  }
  if (typeof parsed !== "object" || parsed === null) throw new CredentialsCorruptError(file);
  const record = parsed;
  for (const key of REQUIRED_KEYS) {
    if (typeof record[key] !== "string") throw new CredentialsCorruptError(file);
  }
  return record;
}
function saveCredentials(creds, env = process.env) {
  const dir = configDir(env);
  mkdirSync(dir, { recursive: true, mode: 448 });
  chmodSync(dir, 448);
  const file = credentialsPath(env);
  const tmp = `${file}.${process.pid}.${randomBytes(6).toString("hex")}.tmp`;
  writeFileSync(tmp, `${JSON.stringify(creds, null, 2)}
`, { mode: 384 });
  chmodSync(tmp, 384);
  renameSync(tmp, file);
}
function clearCredentials(env = process.env) {
  const file = credentialsPath(env);
  if (existsSync(file)) unlinkSync(file);
}
function resolveServerUrl(creds, env = process.env) {
  const fromEnv = env.MOKKAN_SERVER_URL;
  const url = fromEnv && fromEnv !== "" ? fromEnv : creds?.server_url ?? DEFAULT_SERVER_URL;
  return url.replace(/\/+$/, "");
}
var CredentialsLockError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "CredentialsLockError";
  }
};
async function withCredentialsLock(env, fn, opts = {}) {
  const { signal, timeoutMs = 5e3, pollMs = 50, staleMs = 3e4 } = opts;
  const dir = configDir(env);
  mkdirSync(dir, { recursive: true, mode: 448 });
  const file = credentialsLockPath(env);
  const owner = `${process.pid} ${randomBytes(8).toString("hex")}
`;
  const deadline = Date.now() + timeoutMs;
  for (; ; ) {
    try {
      const fd = openSync(file, "wx", 384);
      try {
        writeSync(fd, owner);
      } finally {
        closeSync(fd);
      }
      break;
    } catch (err) {
      if (err.code !== "EEXIST") throw err;
    }
    try {
      if (Date.now() - statSync(file).mtimeMs > staleMs) {
        unlinkSync(file);
        continue;
      }
    } catch (err) {
      if (err.code === "ENOENT") continue;
      throw err;
    }
    if (signal?.aborted) throw new CredentialsLockError(`Gave up waiting for ${file}: deadline exceeded`);
    if (Date.now() >= deadline) {
      throw new CredentialsLockError(`Timed out after ${timeoutMs} ms waiting for ${file} (another mokkan process is refreshing the session; if none is running, delete the file)`);
    }
    await new Promise((resolve) => setTimeout(resolve, pollMs));
  }
  try {
    return await fn();
  } finally {
    try {
      if (readFileSync(file, "utf8") === owner) unlinkSync(file);
    } catch {
    }
  }
}

// src/prompt.ts
import { createInterface } from "node:readline";
import { Writable } from "node:stream";
function promptLine(question, hidden) {
  if (!process.stdin.isTTY || !process.stdout.isTTY) {
    return Promise.reject(new Error("Interactive input required; run this command in a terminal"));
  }
  let muted = false;
  const output = new Writable({
    write(chunk, _encoding, callback) {
      if (!muted) process.stdout.write(chunk);
      callback();
    }
  });
  const rl = createInterface({ input: process.stdin, output, terminal: true });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      if (hidden) process.stdout.write("\n");
      resolve(answer.trim());
    });
    muted = hidden;
  });
}
async function readAllStdin() {
  if (process.stdin.isTTY) return "";
  const chunks = [];
  for await (const chunk of process.stdin) chunks.push(chunk);
  return Buffer.concat(chunks).toString("utf8");
}

// src/commands/auth.ts
var EMAIL_RE = /^[^\s@]+@[^\s@]+$/;
var MIN_PASSWORD_LENGTH = 10;
async function requireEmail(ctx, given, usage) {
  const email = given ?? (ctx.io.isTTY ? await ctx.io.prompt("Email: ", false) : "");
  if (!EMAIL_RE.test(email)) throw new UserError(`Provide an email address. Usage: ${usage}`);
  return email;
}
async function requirePassword(ctx, question) {
  const fromEnv = ctx.io.env.MOKKAN_PASSWORD;
  if (fromEnv && fromEnv !== "") return fromEnv;
  if (!ctx.io.isTTY) throw new UserError("A password is needed: run this in a terminal, or set MOKKAN_PASSWORD");
  return ctx.io.prompt(question, true);
}
async function requireOtp(ctx, email) {
  const flag = ctx.flags.otp;
  if (typeof flag === "string" && flag !== "") return flag;
  if (!ctx.io.isTTY) throw new UserError(`Provide the code: mokkan register --complete ${email} --otp <code>`);
  return ctx.io.prompt("One-time code: ", false);
}
async function registerCommand(ctx, args) {
  const { io, client, flags } = ctx;
  const email = await requireEmail(ctx, args[0], "mokkan register you@example.com");
  if (flags.complete !== true) {
    await client.registerStart(email);
    io.stdout(`One-time code sent to ${email}. (Dev server: read it from GET /dev/outbox?to=${email} or server/outbox.jsonl.)
`);
    if (flags.start === true) return 0;
    if (!io.isTTY) {
      io.stdout(`Finish in a terminal: mokkan register --complete ${email}
`);
      return 0;
    }
  }
  const otp = await requireOtp(ctx, email);
  const password = await requirePassword(ctx, `New password (min ${MIN_PASSWORD_LENGTH} chars): `);
  if (password.length < MIN_PASSWORD_LENGTH) throw new UserError(`Password must be at least ${MIN_PASSWORD_LENGTH} characters`);
  const creds = await client.registerComplete(email, otp, password);
  io.stdout(`Registered and logged in as ${creds.email} (${client.baseUrl}).
`);
  return 0;
}
async function loginCommand(ctx, args) {
  const email = await requireEmail(ctx, args[0], "mokkan login you@example.com");
  const fromEnv = ctx.io.env.MOKKAN_PASSWORD;
  if (!ctx.io.isTTY && (fromEnv === void 0 || fromEnv === "")) {
    ctx.io.stdout(`Finish in a terminal: mokkan login ${email}
`);
    return 0;
  }
  const password = await requirePassword(ctx, "Password: ");
  const creds = await ctx.client.login(email, password);
  ctx.io.stdout(`Logged in as ${creds.email} (${ctx.client.baseUrl}).
`);
  return 0;
}
async function logoutCommand(ctx) {
  if (!ctx.client.hasCredentials()) {
    ctx.io.stdout("Not logged in.\n");
    return 0;
  }
  try {
    await ctx.client.logout();
  } catch (err) {
    if (!(err instanceof NetworkError) && !(err instanceof ApiError)) throw err;
  }
  clearCredentials(ctx.io.env);
  ctx.io.stdout("Logged out.\n");
  return 0;
}
async function statusCommand(ctx) {
  const { io, client } = ctx;
  if (!client.hasCredentials()) {
    io.stdout(`Server: ${client.baseUrl}
Not logged in. Run: mokkan login
`);
    return 0;
  }
  const [me, list, pending] = await Promise.all([client.me(), client.list("active"), client.pending()]);
  if (ctx.json) {
    io.stdout(`${JSON.stringify({ server_url: client.baseUrl, me, active: list.reminders.length, due: pending.due.length, awaiting_ack: pending.awaiting_ack.length })}
`);
    return 0;
  }
  io.stdout([
    `Server: ${client.baseUrl}`,
    `Account: ${me.email}`,
    ...typeof me.credit_balance === "number" ? [`Credits: ${me.credit_balance}`] : [],
    `Session: ${me.session_active ? "active" : "inactive"} (last heartbeat ${me.last_heartbeat_at ?? "never"})`,
    `Active reminders: ${list.reminders.length}`,
    `Due now: ${pending.due.length}, awaiting ack: ${pending.awaiting_ack.length}`,
    ""
  ].join("\n"));
  return 0;
}

// src/format.ts
function shortId(id) {
  return id.slice(0, 8);
}
function formatRelative(target, now) {
  const diff = Math.round((target.getTime() - now.getTime()) / 1e3);
  const abs = Math.abs(diff);
  const unit = abs >= 86400 ? `${Math.floor(abs / 86400)}d` : abs >= 3600 ? `${Math.floor(abs / 3600)}h` : abs >= 60 ? `${Math.floor(abs / 60)}m` : `${abs}s`;
  return diff >= 0 ? `in ${unit}` : `${unit} ago`;
}
function formatReminderLine(r) {
  return `- [${shortId(r.id)}] ${r.text}${r.due_at ? ` (due ${r.due_at})` : ""}`;
}
function formatList(reminders, now) {
  if (reminders.length === 0) return "No reminders.\n";
  const lines = reminders.map((r, i) => {
    const due = r.due_at ? `  due ${r.due_at} (${formatRelative(new Date(r.due_at), now)})` : "";
    return `${String(i + 1).padStart(2)}. [${shortId(r.id)}] ${r.state.padEnd(12)} ${r.text}${due}`;
  });
  return `${lines.join("\n")}
`;
}
var ACK_HINT = "run /mokkan ack <id> or /mokkan ack all";
function formatPending(p) {
  if (p.due.length === 0 && p.awaiting_ack.length === 0) return "";
  const lines = ["Reminders (mokkan):"];
  for (const r of p.due) lines.push(formatReminderLine(r));
  if (p.awaiting_ack.length > 0) {
    lines.push(`${p.awaiting_ack.length} reminder(s) awaiting acknowledgment \u2014 ${ACK_HINT}`);
  }
  return `${lines.join("\n")}
`;
}

// src/commands/list.ts
async function listCommand(ctx) {
  const res = await ctx.client.list(ctx.flags.all === true ? "all" : "active");
  ctx.io.stdout(ctx.json ? `${JSON.stringify(res)}
` : formatList(res.reminders, ctx.now()));
  return 0;
}
async function doneCommand(ctx) {
  const res = await ctx.client.list("done");
  ctx.io.stdout(ctx.json ? `${JSON.stringify(res)}
` : formatList(res.reminders, ctx.now()));
  return 0;
}
async function pendingCommand(ctx) {
  const res = await ctx.client.pending();
  if (ctx.json) {
    ctx.io.stdout(`${JSON.stringify(res)}
`);
    return 0;
  }
  ctx.io.stdout(formatPending(res) || "Nothing pending.\n");
  return 0;
}

// src/duration.ts
var DURATION_RE = /^(?:(\d+)d)?(?:(\d+)h)?(?:(\d+)m)?(?:(\d+)s)?$/;
function parseDuration(input) {
  const s = input.trim();
  const m = DURATION_RE.exec(s);
  if (!s || !m || m.slice(1).every((part2) => part2 === void 0)) {
    throw new Error(`Invalid duration "${input}" (examples: 30s, 10m, 2h, 1d, 1h30m)`);
  }
  const [d, h, min, sec] = m.slice(1).map((part2) => part2 === void 0 ? 0 : Number(part2));
  return d * 86400 + h * 3600 + min * 60 + sec;
}

// src/commands/mutate.ts
async function pushCommand(ctx, args) {
  const text = args.join(" ").trim();
  if (text === "") throw new UserError("Usage: mokkan push <text>");
  const res = await ctx.client.push(text);
  ctx.io.stdout(ctx.json ? `${JSON.stringify(res)}
` : `Pushed [${shortId(res.reminder.id)}] ${res.reminder.text}
`);
  return 0;
}
async function takeCommand(ctx, end) {
  try {
    const res = end === "pop" ? await ctx.client.pop() : await ctx.client.dequeue();
    const verb = end === "pop" ? "Popped" : "Dequeued";
    ctx.io.stdout(ctx.json ? `${JSON.stringify(res)}
` : `${verb} [${shortId(res.reminder.id)}] ${res.reminder.text}
`);
    return 0;
  } catch (err) {
    if (err instanceof ApiError && err.code === "empty") {
      ctx.io.stdout(ctx.json ? `${JSON.stringify({ error: "empty", message: "List is empty." })}
` : "List is empty.\n");
      return 1;
    }
    throw err;
  }
}
async function inCommand(ctx, args) {
  if (args.length < 2) throw new UserError("Usage: mokkan in <duration> <text>   (e.g. mokkan in 30m call mom)");
  let seconds;
  try {
    seconds = parseDuration(args[0]);
  } catch (err) {
    throw new UserError(err.message);
  }
  const text = args.slice(1).join(" ").trim();
  if (text === "") throw new UserError("Usage: mokkan in <duration> <text>");
  const now = ctx.now();
  const dueAt = new Date(now.getTime() + seconds * 1e3);
  if (!Number.isFinite(dueAt.getTime())) throw new UserError("duration is too large");
  const res = await ctx.client.push(text, dueAt);
  ctx.io.stdout(ctx.json ? `${JSON.stringify(res)}
` : `Scheduled [${shortId(res.reminder.id)}] "${res.reminder.text}" for ${dueAt.toISOString()} (${formatRelative(dueAt, now)})
`);
  return 0;
}
function resolvePrefixes(reminders, prefixes, listCommand2 = "mokkan list") {
  const ids = /* @__PURE__ */ new Set();
  for (const prefix of prefixes) {
    const matches = reminders.filter((r) => r.id.startsWith(prefix));
    const kind = listCommand2 === "mokkan list" ? "active " : listCommand2 === "mokkan done" ? "finished " : "";
    if (matches.length === 0) throw new UserError(`No ${kind}reminder matches "${prefix}" (run: ${listCommand2})`);
    if (matches.length > 1) throw new UserError(`"${prefix}" is ambiguous: ${matches.map((r) => shortId(r.id)).sort().join(", ")}`);
    ids.add(matches[0].id);
  }
  return [...ids];
}
async function ackCommand(ctx, args) {
  if (args.length === 0) throw new UserError("Usage: mokkan ack <id-prefix>... | mokkan ack all");
  let acknowledged;
  if (args[0] === "all") {
    acknowledged = (await ctx.client.ack("all")).acknowledged;
  } else {
    acknowledged = await ackWithRetry(ctx, args);
  }
  ctx.io.stdout(ctx.json ? `${JSON.stringify({ acknowledged })}
` : `Acknowledged ${acknowledged.length} reminder(s).
`);
  return 0;
}
async function markDoneCommand(ctx, args, done) {
  const verb = done ? "done" : "undone";
  if (args.length === 0) throw new UserError(`Usage: mokkan ${verb} <id-prefix>...`);
  const changed = [];
  for (let attempt = 0; ; attempt++) {
    const list = await ctx.client.list(done ? "all" : "done");
    const ids = resolvePrefixes(list.reminders, args, done ? "mokkan list --all" : "mokkan done");
    try {
      let version = list.version;
      for (const id of ids) {
        const res = await ctx.client.setDone(id, done, version);
        version = res.version;
        changed.push(res.reminder);
      }
      break;
    } catch (err) {
      if (err instanceof ApiError && err.code === "stale" && attempt === 0) {
        changed.length = 0;
        continue;
      }
      throw err;
    }
  }
  if (ctx.json) {
    ctx.io.stdout(`${JSON.stringify({ [done ? "done" : "reopened"]: changed.map((r) => r.id) })}
`);
  } else {
    for (const r of changed) ctx.io.stdout(`${done ? "Done" : "Reopened"} [${shortId(r.id)}] ${r.text}
`);
  }
  return 0;
}
async function ackWithRetry(ctx, prefixes) {
  for (let attempt = 0; ; attempt++) {
    const list = await ctx.client.list("active");
    const ids = resolvePrefixes(list.reminders, prefixes);
    try {
      return (await ctx.client.ack(ids, list.version)).acknowledged;
    } catch (err) {
      if (err instanceof ApiError && err.code === "stale" && attempt === 0) continue;
      throw err;
    }
  }
}
var POSITION_RE = /^\d{1,3}$/;
var ISO_WITH_ZONE_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2}(\.\d{1,9})?)?(Z|[+-]\d{2}:?\d{2})$/i;
var EDIT_USAGE = "Usage: mokkan edit <n|id> [--all] [--in <duration> | --at <iso> | --clear-due] [new text...]";
function listCommandName(scope) {
  return scope === "all" ? "mokkan list --all" : "mokkan list";
}
function resolveEditTarget(list, target) {
  if (target.kind === "prefix") {
    return resolvePrefixes(list, [target.prefix], "mokkan list --all")[0];
  }
  if (target.n < 1 || target.n > list.length) {
    throw new UserError(`There is no reminder number ${target.n} in \`${listCommandName(target.scope)}\` (it shows ${list.length}).`);
  }
  return list[target.n - 1].id;
}
function buildEditPatch(ctx, words, now) {
  const { text: textFlag, in: inFlag, at, "clear-due": clearDue } = ctx.flags;
  for (const [name, value] of [["text", textFlag], ["in", inFlag], ["at", at]]) {
    if (value === "") throw new UserError(`--${name} needs a value.
${EDIT_USAGE}`);
  }
  const timeFlags = [inFlag !== void 0, at !== void 0, clearDue === true].filter(Boolean).length;
  if (timeFlags > 1) throw new UserError("Use either --in, --at or --clear-due, not several.");
  const positionalText = words.join(" ").trim();
  if (textFlag !== void 0 && words.length > 0) {
    throw new UserError(`Give the new text either after the target or with --text, not both.
${EDIT_USAGE}`);
  }
  const rawText = textFlag !== void 0 ? String(textFlag).trim() : positionalText;
  if (textFlag !== void 0 && rawText === "") throw new UserError("--text must not be empty.");
  if (rawText === "" && timeFlags === 0) {
    throw new UserError(`There is nothing to change: give new text and/or --in, --at or --clear-due.
${EDIT_USAGE}`);
  }
  const patch = {};
  if (rawText !== "") patch.text = rawText;
  if (inFlag !== void 0) {
    let seconds;
    try {
      seconds = parseDuration(String(inFlag));
    } catch (err) {
      throw new UserError(err.message);
    }
    const due = new Date(now.getTime() + seconds * 1e3);
    if (!Number.isFinite(due.getTime())) throw new UserError("duration is too large");
    patch.due_at = due;
  } else if (at !== void 0) {
    const due = new Date(String(at));
    if (!ISO_WITH_ZONE_RE.test(String(at)) || Number.isNaN(due.getTime())) {
      throw new UserError(`Invalid --at "${String(at)}" (use an ISO time with a zone, such as 2026-10-01T09:00:00Z or 2026-10-01T11:00:00+02:00)`);
    }
    patch.due_at = due;
  } else if (clearDue === true) {
    patch.due_at = null;
  }
  return patch;
}
async function editCommand(ctx, args) {
  if (args.length === 0) throw new UserError(EDIT_USAGE);
  const now = ctx.now();
  const patch = buildEditPatch(ctx, args.slice(1), now);
  const target = POSITION_RE.test(args[0]) ? { kind: "number", n: Number(args[0]), scope: ctx.flags.all === true ? "all" : "active" } : { kind: "prefix", prefix: args[0] };
  const scope = target.kind === "number" ? target.scope : "all";
  let list = await ctx.client.list(scope);
  const id = resolveEditTarget(list.reminders, target);
  for (let attempt = 0; ; attempt++) {
    try {
      const res = await ctx.client.editReminder(id, patch, list.version);
      const r = res.reminder;
      ctx.io.stdout(ctx.json ? `${JSON.stringify(res)}
` : `Edited [${shortId(r.id)}] ${r.text}${r.due_at ? ` (due ${r.due_at}, ${formatRelative(new Date(r.due_at), now)})` : ""}
`);
      return 0;
    } catch (err) {
      if (err instanceof ApiError && err.code === "not_editable") {
        throw new UserError("This reminder was already shown or emailed, so --in/--at/--clear-due no longer apply (its text can still be edited).");
      }
      if (!(err instanceof ApiError && err.code === "stale" && attempt === 0)) throw err;
    }
    list = await ctx.client.list(scope);
    if (target.kind === "number") {
      const current = list.reminders[target.n - 1];
      if (current?.id !== id) throw new UserError(`The list changed; run ${listCommandName(target.scope)} and try again.`);
    }
  }
}

// src/commands/billing.ts
import { spawn as nodeSpawn } from "node:child_process";
function isTrustedCheckoutUrl(url) {
  let u;
  try {
    u = new URL(url);
  } catch {
    return false;
  }
  const host = u.hostname.toLowerCase();
  return u.protocol === "https:" && (host === "checkout.stripe.com" || host.endsWith(".stripe.com"));
}
function openUrlDetached(url, platform = process.platform, env = process.env, spawn = nodeSpawn) {
  if (!isTrustedCheckoutUrl(url)) return false;
  let cmd;
  let args;
  if (platform === "darwin") {
    cmd = "open";
    args = [url];
  } else if (platform === "win32") {
    cmd = "rundll32";
    args = ["url.dll,FileProtocolHandler", url];
  } else {
    if (!env.DISPLAY && !env.WAYLAND_DISPLAY) return false;
    cmd = "xdg-open";
    args = [url];
  }
  try {
    const child = spawn(cmd, args, { detached: true, stdio: "ignore", windowsHide: true, env });
    child.on("error", () => void 0);
    child.unref();
    return true;
  } catch {
    return false;
  }
}
async function buyCommand(ctx) {
  if (ctx.flags.pack === "") throw new UserError("--pack needs a value.\nUsage: mokkan buy [--pack <key>] [--no-open]");
  const pack = typeof ctx.flags.pack === "string" ? ctx.flags.pack : void 0;
  let res;
  try {
    res = await ctx.client.checkout(pack);
  } catch (err) {
    if (err instanceof ApiError && err.status === 404) throw new UserError("Billing is not enabled on this server.");
    throw err;
  }
  const wanted = ctx.flags["no-open"] !== true;
  const trusted = isTrustedCheckoutUrl(res.url);
  if (wanted && trusted) {
    try {
      ctx.io.openUrl?.(res.url);
    } catch {
    }
  }
  if (ctx.json) {
    ctx.io.stdout(`${JSON.stringify(res)}
`);
    return 0;
  }
  let how;
  if (!wanted) how = "Open the link above in your browser to pay.";
  else if (trusted) how = "Opening it in your browser (open the link above if nothing appears).";
  else how = "This link was not opened automatically because it is not a Stripe Checkout (https://checkout.stripe.com) address. Check it before opening it.";
  ctx.io.stdout([
    `Checkout: ${res.url}`,
    how,
    "When the payment completes, run `mokkan balance` to see your credits.",
    ""
  ].join("\n"));
  return 0;
}
async function balanceCommand(ctx) {
  const res = await ctx.client.balance();
  if (ctx.json) {
    ctx.io.stdout(`${JSON.stringify(res)}
`);
    return 0;
  }
  const lines = [`Balance: ${res.balance} ${Math.abs(res.balance) === 1 ? "credit" : "credits"}`];
  if (res.ledger.length === 0) {
    lines.push("No transactions yet.");
  } else {
    lines.push("", "Recent transactions (UTC):");
    for (const e of res.ledger) {
      const when = e.created_at.replace("T", " ").slice(0, 16);
      const delta = e.delta > 0 ? `+${e.delta}` : String(e.delta);
      lines.push(`  ${when}  ${delta.padStart(6)}  ${e.reason}`);
    }
  }
  ctx.io.stdout(`${lines.join("\n")}
`);
  return 0;
}

// src/commands/heartbeat.ts
async function heartbeatCommand(ctx) {
  const source = typeof ctx.flags.source === "string" && ctx.flags.source !== "" ? ctx.flags.source : "cli";
  const res = await ctx.client.heartbeat(source);
  ctx.io.stdout(ctx.json ? `${JSON.stringify(res)}
` : `Heartbeat sent (${source}); session active until ${res.active_until}.
`);
  return 0;
}

// src/text.ts
var MAX_TEXT = 40;
function cleanText(text, max = MAX_TEXT) {
  const flat = text.replace(/[\u0000-\u001f\u007f-\u009f]/g, " ").replace(/\s+/g, " ").trim();
  return flat.length > max ? `${flat.slice(0, max - 1)}\u2026` : flat;
}
function formatAge(ms) {
  const s = Math.max(0, Math.floor(ms / 1e3));
  if (s >= 86400) return `${Math.floor(s / 86400)}d`;
  if (s >= 3600) return `${Math.floor(s / 3600)}h`;
  if (s >= 60) return `${Math.floor(s / 60)}m`;
  return `${s}s`;
}

// src/tui/state.ts
var CHROME_ROWS = 7;
var MAX_INPUT_CODE_POINTS = 2e3;
var ACTIVE_STATES = /* @__PURE__ */ new Set(["due", "delivered", "acknowledged"]);
function emptyLogin() {
  return { field: "email", email: "", password: "", cursor: 0, busy: false, error: null };
}
function initialState(email, host) {
  return {
    screen: email === null ? "login" : "dashboard",
    login: emptyLogin(),
    tab: "stack",
    reminders: [],
    done: null,
    version: null,
    selected: 0,
    scroll: 0,
    email: email ?? "",
    host,
    credits: null,
    fetchedAt: null,
    refreshing: false,
    error: null,
    message: null,
    mode: { kind: "normal" }
  };
}
function rowsOf(state) {
  return state.tab === "done" ? state.done ?? [] : state.reminders;
}

// src/tui/text.ts
var segmenter;
var WIDE = [
  [4352, 4447],
  [8986, 8987],
  [9193, 9196],
  [9200, 9200],
  [9203, 9203],
  [9725, 9726],
  [9748, 9749],
  [9800, 9811],
  [9855, 9855],
  [9875, 9875],
  [9889, 9889],
  [9898, 9899],
  [9917, 9918],
  [9924, 9925],
  [9934, 9934],
  [9940, 9940],
  [9962, 9962],
  [9970, 9971],
  [9973, 9973],
  [9978, 9978],
  [9981, 9981],
  [9989, 9989],
  [9994, 9995],
  [10024, 10024],
  [10060, 10060],
  [10062, 10062],
  [10067, 10069],
  [10071, 10071],
  [10133, 10135],
  [10160, 10160],
  [10175, 10175],
  [11035, 11036],
  [11088, 11088],
  [11093, 11093],
  [11904, 42191],
  [44032, 55203],
  [63744, 64255],
  [65072, 65103],
  [65280, 65376],
  [65504, 65510],
  [126980, 126980],
  [127183, 127183],
  [127374, 127374],
  [127377, 127386],
  [127462, 127487],
  [127489, 127569],
  [127744, 128591],
  [128640, 128767],
  [128992, 129003],
  [129280, 129535],
  [129648, 129791],
  [131072, 262141]
];
function isWide(cp) {
  for (const [lo, hi] of WIDE) {
    if (cp < lo) return false;
    if (cp <= hi) return true;
  }
  return false;
}
function graphemes(text) {
  segmenter ??= new Intl.Segmenter(void 0, { granularity: "grapheme" });
  return [...segmenter.segment(text)].map((s) => s.segment);
}
function graphemeWidth(g) {
  if (g.includes("\uFE0F")) return 2;
  for (const c of g) if (isWide(c.codePointAt(0))) return 2;
  return 1;
}
function displayWidth(text) {
  let w = 0;
  for (const g of graphemes(text)) w += graphemeWidth(g);
  return w;
}
function fit(text, width) {
  if (width <= 0) return "";
  if (displayWidth(text) <= width) return text;
  let out = "";
  let used = 0;
  for (const g of graphemes(text)) {
    const w = graphemeWidth(g);
    if (used + w > width - 1) break;
    out += g;
    used += w;
  }
  return `${out}\u2026`;
}
function padEnd(text, width) {
  return text + " ".repeat(Math.max(0, width - displayWidth(text)));
}
function padStart(text, width) {
  return " ".repeat(Math.max(0, width - displayWidth(text))) + text;
}

// src/tui/screen.ts
var MIN_COLUMNS = 20;
var MIN_ROWS = 8;
var MIN_TEXT_COLUMNS = 10;
var TIME_GAP_COLUMNS = 2;
var LOW_CREDITS = 10;
var HEADER_LEFT_MIN = 24;
var LOGIN_FIELD_COLUMN = 13;
var SGR = { red: "31", yellow: "33", green: "32", dim: "2", plain: "", bold: "1" };
function paint(text, ...styles) {
  const codes = styles.map((s) => SGR[s]).filter((c) => c !== "");
  return codes.length === 0 || text === "" ? text : `\x1B[${codes.join(";")}m${text}\x1B[0m`;
}
var part = (text, ...styles) => ({ text, styles });
var partsWidth = (parts) => parts.reduce((n, p) => n + displayWidth(p.text), 0);
var clean = (text) => cleanText(text, Number.MAX_SAFE_INTEGER);
var blankControls = (text) => text.replace(/[\u0000-\u001f\u007f-\u009f]/g, " ");
function cut(parts, columns) {
  const out = [];
  let left = columns;
  for (const p of parts) {
    const w = displayWidth(p.text);
    if (w <= left) {
      out.push(p);
      left -= w;
      continue;
    }
    if (left > 0) out.push({ text: fit(p.text, left), styles: p.styles });
    break;
  }
  return out;
}
var paintParts = (parts, extra) => parts.map((p) => paint(p.text, ...p.styles, ...extra)).join("");
function line(left, right, columns, opts = {}) {
  const rw = partsWidth(right);
  const reserved = rw + (opts.minGap ?? 1);
  const keepRight = rw > 0 && columns - reserved >= (opts.minLeft ?? 8);
  const l = cut(left, keepRight ? columns - reserved : columns);
  const r = keepRight ? right : [];
  const gap = " ".repeat(Math.max(0, columns - partsWidth(l) - partsWidth(r)));
  const extra = opts.rowStyle ? [opts.rowStyle] : [];
  return paintParts(l, extra) + (opts.rowStyle ? paint(gap, opts.rowStyle) : gap) + paintParts(r, extra);
}
function inputWindow(buffer, cursor, width) {
  const gs = graphemes(buffer);
  const before = [0];
  for (const g of gs) before.push(before[before.length - 1] + graphemeWidth(g));
  let at = 0;
  for (let seen = 0; at < gs.length && seen < cursor; at++) seen += [...gs[at]].length;
  let start = 0;
  while (start < at && before[at] - before[start] >= width) start++;
  let end = at;
  while (end < gs.length && before[end + 1] - before[start] <= width) end++;
  return { text: gs.slice(start, end).join(""), cursorColumn: before[at] - before[start] };
}
var drawable = (size) => ({ columns: size.columns - 1, rows: size.rows });
function render(state, size, now) {
  const { columns, rows } = size;
  let lines;
  if (columns < MIN_COLUMNS || rows < MIN_ROWS) {
    lines = [fit("mokkan ui: terminal too small", columns - 1)];
  } else if (state.screen === "login") {
    lines = loginLines(state, drawable(size));
  } else {
    lines = dashboardLines(state, drawable(size), now);
  }
  while (lines.length < rows) lines.push("");
  return lines.slice(0, rows).map((l) => `${l}\x1B[0m`);
}
function cursorPosition(state, size) {
  if (size.columns < MIN_COLUMNS || size.rows < MIN_ROWS) return null;
  const { columns } = drawable(size);
  if (state.screen === "login") {
    const l = state.login;
    const value = l.field === "email" ? l.email : "\u2022".repeat([...l.password].length);
    const { cursorColumn: cursorColumn2 } = inputWindow(value, l.cursor, columns - LOGIN_FIELD_COLUMN);
    return { row: l.field === "email" ? 5 : 6, column: LOGIN_FIELD_COLUMN + cursorColumn2 + 1 };
  }
  if (state.mode.kind !== "input") return null;
  const labelWidth = displayWidth(` ${clean(state.mode.label)} \u203A `);
  const { cursorColumn } = inputWindow(blankControls(state.mode.buffer), state.mode.cursor, columns - labelWidth);
  return { row: size.rows - 1, column: labelWidth + cursorColumn + 1 };
}
function dashboardLines(state, size, now) {
  const { columns, rows } = size;
  const out = [header(state, columns, now), tabs(state, columns), "\u2500".repeat(columns)];
  const listRows = rows - CHROME_ROWS;
  const items = rowsOf(state);
  const list = [];
  if (items.length === 0) {
    const empty = state.tab === "done" ? "Nothing finished yet." : "Nothing on the stack. p adds a todo, i a reminder.";
    list.push(line([part(` ${empty}`, "dim")], [], columns));
  } else {
    const numberWidth = String(items.length).length;
    for (let idx = state.scroll; idx < Math.min(items.length, state.scroll + listRows); idx++) {
      const selected = idx === state.selected;
      list.push(row(items[idx], idx, numberWidth, selected, columns, now));
      if (selected) list.push(line([part(" ".repeat(rowPrefixWidth(numberWidth))), part(detail(items[idx], now), "dim")], [], columns));
    }
  }
  while (list.length < listRows + 1) list.push("");
  out.push(...list);
  const m = state.message;
  out.push(m ? line([part(` ${m.tone === "red" ? "error: " : ""}${clean(m.text)}`, m.tone)], [], columns) : "");
  out.push(...footer(state, columns));
  return out;
}
function header(state, columns, now) {
  const left = [part(" mokkan", "bold"), part(` \xB7 ${clean(state.email)}`)];
  const c = state.credits;
  if (typeof c === "number" && Number.isFinite(c)) {
    left.push(c <= 0 ? part(` \xB7 ${c} credits \xB7 buy`, "red") : c < LOW_CREDITS ? part(` \xB7 ${c} credits \xB7 low`, "yellow") : part(` \xB7 ${c} credits`, "dim"));
  }
  left.push(part(` \xB7 ${state.host}`));
  return line(left, [status(state, now, Math.max(8, columns - 2 - HEADER_LEFT_MIN))], columns);
}
function status(state, now, maxWidth) {
  const age = state.fetchedAt ? formatAge(now.getTime() - state.fetchedAt.getTime()) : null;
  if (state.refreshing) return part("syncing\u2026", "dim");
  if (state.error) {
    const suffix = age ? ` \xB7 ${age} old` : "";
    if (state.error.kind === "offline") return part(`offline${suffix}`, "yellow");
    const msg = fit(clean(state.error.message), Math.max(1, maxWidth - displayWidth("error: ") - displayWidth(suffix)));
    return part(`error: ${msg}${suffix}`, "red");
  }
  return part(age ? `synced ${age}` : "loading\u2026", "dim");
}
function tabs(state, columns) {
  const labels = [["stack", `Stack ${state.reminders.length}`], ["done", state.done ? `Done ${state.done.length}` : "Done"]];
  const parts = [part(" ")];
  labels.forEach(([tab, label], i) => {
    if (i > 0) parts.push(part(" \u2502 ", "dim"));
    parts.push(part(label, tab === state.tab ? "bold" : "dim"));
  });
  return line(parts, [], columns);
}
var isTodo = (r) => r.due_at === null;
function glyph(r, now) {
  if (r.state === "done") return part("\u2713", "dim");
  if (isTodo(r)) return part("\u25A1", r.state === "acknowledged" ? "dim" : "plain");
  if (r.state === "due" || r.state === "scheduled" && Date.parse(r.due_at) <= now.getTime()) return part("\u25CF", "yellow");
  if (r.state === "scheduled") return part("\u25F7", "dim");
  if (r.state === "delivered") return part("\u25CB");
  return part("\xB7", "dim");
}
function formatAhead(at, now) {
  const time = at.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", hour12: false });
  if (at.toDateString() === now.toDateString()) return time;
  if (at.getTime() - now.getTime() < 7 * 864e5) return `${at.toLocaleDateString("en-US", { weekday: "short" })} ${time}`;
  return at.toLocaleDateString("en-GB", { day: "numeric", month: "short" });
}
function timing(r, now) {
  if (isTodo(r)) return null;
  const due = Date.parse(r.due_at);
  if (Number.isNaN(due)) return null;
  const t = now.getTime();
  if (due > t) return part(due - t < 36e5 ? `in ${formatAge(due - t)}` : formatAhead(new Date(due), now), "dim");
  if (r.state === "due" || r.state === "scheduled") return part(`overdue ${formatAge(t - due)}`, "red");
  return part(`${formatAge(t - due)} ago`, "dim");
}
var rowPrefixWidth = (numberWidth) => 4 + numberWidth + 2;
function row(r, index, numberWidth, selected, columns, now) {
  const when = timing(r, now);
  const left = [part(`${selected ? "\u25B8" : " "} `), glyph(r, now), part(` ${padStart(String(index + 1), numberWidth)}: ${clean(r.text)}`)];
  return line(left, when ? [when] : [], columns, {
    minLeft: rowPrefixWidth(numberWidth) + MIN_TEXT_COLUMNS,
    minGap: TIME_GAP_COLUMNS,
    rowStyle: selected ? "bold" : void 0
  });
}
function detail(r, now) {
  const ago = (at) => `${formatAge(now.getTime() - Date.parse(at))} ago`;
  const pushed = `pushed ${ago(r.created_at)}`;
  if (r.state === "done") return r.done_at ? `done ${ago(r.done_at)} \xB7 ${pushed}` : `done \xB7 ${pushed}`;
  const parts = [isTodo(r) ? "todo" : "reminder", pushed];
  if (r.delivered_at) parts.push(`seen ${ago(r.delivered_at)}`);
  if (r.acknowledged_at) parts.push("acked");
  return parts.join(" \xB7 ");
}
function footer(state, columns) {
  const m = state.mode;
  if (m.kind === "input") {
    const label = ` ${clean(m.label)} \u203A `;
    const { text } = inputWindow(blankControls(m.buffer), m.cursor, columns - displayWidth(label));
    return [line([part(label, "bold"), part(text)], [], columns), line([part(` ${m.hint}`, "dim")], [], columns)];
  }
  if (m.kind === "confirm") {
    const room = columns - displayWidth(` ${m.action} ""?  y: yes  n: no`);
    return [line([part(` ${m.action} "${fit(clean(m.text), room)}"?  y: yes  n: no`, "yellow")], [], columns), ""];
  }
  return [
    line([part(" p todo \xB7 i remind \xB7 e edit \xB7 t time \xB7 a done \xB7 k ack \xB7 s view", "dim")], [], columns),
    line([part(" x pop \xB7 d dequeue \xB7 K ack all \xB7 r refresh \xB7 b buy \xB7 q quit \xB7 \u2191\u2193 1-9 move", "dim")], [], columns)
  ];
}
function loginLines(state, size) {
  const { columns } = size;
  const l = state.login;
  const field = (label, value, active) => {
    const { text } = inputWindow(value, active ? l.cursor : [...value].length, columns - LOGIN_FIELD_COLUMN);
    return line([part(` ${padEnd(label, 9)} \u203A `, active ? "bold" : "dim"), part(text)], [], columns);
  };
  return [
    line([part(" mokkan", "bold"), part(` \xB7 ${state.host}`)], [part("not logged in", "dim")], columns),
    "",
    line([part(" Log in", "bold")], [], columns),
    "",
    field("Email", l.email, l.field === "email"),
    field("Password", "\u2022".repeat([...l.password].length), l.field === "password"),
    "",
    l.error ? line([part(` ${clean(l.error.text)}`, l.error.tone)], [], columns) : "",
    "",
    line([part(" Enter next field / log in \xB7 Tab switch field \xB7 Esc quit", "dim")], [], columns),
    line([part(" No account? Quit and run: mokkan register you@example.com", "dim")], [], columns)
  ];
}

// src/tui/app.ts
var REFRESH_INTERVAL_MS = 1e4;
function errorText(err) {
  return err instanceof Error ? err.message : String(err);
}
var isStale = (err) => err instanceof ApiError && err.status === 409 && err.code === "stale";
function editLine(line2, key) {
  const chars = [...line2.buffer];
  const room = Math.max(0, MAX_INPUT_CODE_POINTS - chars.length);
  switch (key.name) {
    case "left":
      line2.cursor = Math.max(0, line2.cursor - 1);
      break;
    case "right":
      line2.cursor = Math.min(chars.length, line2.cursor + 1);
      break;
    case "home":
      line2.cursor = 0;
      break;
    case "end":
      line2.cursor = chars.length;
      break;
    case "backspace":
      if (line2.cursor > 0) {
        chars.splice(line2.cursor - 1, 1);
        line2.cursor -= 1;
      }
      break;
    case "delete":
      chars.splice(line2.cursor, 1);
      break;
    case "ctrl-u":
      chars.length = 0;
      line2.cursor = 0;
      break;
    case "char":
      if (room > 0) {
        chars.splice(line2.cursor, 0, key.ch);
        line2.cursor += 1;
      }
      break;
    case "paste": {
      const added = [];
      for (const c of key.text) {
        if (added.length >= room) break;
        added.push(c);
      }
      chars.splice(line2.cursor, 0, ...added);
      line2.cursor += added.length;
      break;
    }
    default:
      return false;
  }
  line2.buffer = chars.join("");
  return true;
}
var TuiApp = class {
  state;
  /** Set when the app wants to quit; the driver resolves with it. */
  exitCode = null;
  /** Called after every state change; the driver redraws. */
  onChange = () => void 0;
  size = { columns: 80, rows: 24 };
  queue = Promise.resolve();
  /** The refresh that is queued or running; asking for another one joins it. */
  pendingRefresh = null;
  /** Ids already sent to /reminders/deliver, so a slow server never gets them twice. */
  delivered = /* @__PURE__ */ new Set();
  client;
  now;
  openUrl;
  constructor(opts) {
    this.client = opts.client;
    this.now = opts.now;
    this.openUrl = opts.openUrl;
    this.state = initialState(opts.email, opts.host);
  }
  setSize(size) {
    this.size = size;
    this.clampSelection();
  }
  rows() {
    return rowsOf(this.state);
  }
  render(size, now) {
    return render(this.state, size, now);
  }
  refresh() {
    this.pendingRefresh ??= this.enqueue(() => this.doRefresh()).finally(() => {
      this.pendingRefresh = null;
    });
    return this.pendingRefresh;
  }
  handleKey(key) {
    const s = this.state;
    if (s.screen === "login") return this.loginKey(key);
    if (s.mode.kind === "input") return this.inputKey(s.mode, key);
    if (key.name === "paste") return Promise.resolve();
    if (s.mode.kind === "confirm") return this.confirmKey(s.mode, key);
    return this.normalKey(key);
  }
  normalKey(key) {
    const ch = key.name === "char" ? key.ch : "";
    if (ch === "q" || key.name === "ctrl-c") return this.quit();
    if (key.name === "up") return this.move(-1);
    if (key.name === "down") return this.move(1);
    if (key.name === "home") return this.move(-Infinity);
    if (key.name === "end") return this.move(Infinity);
    if (ch >= "1" && ch <= "9") return this.jump(Number(ch) - 1);
    if (key.name === "tab" || ch === "s") return this.switchView();
    if (ch === "r") return this.refresh();
    if (ch === "p") return this.startInput("push", "todo", "text (1 credit) \xB7 Enter to push \xB7 Esc to cancel");
    if (ch === "i") return this.startInput("in", "remind", "2h call the bank (1 credit + 1 reserved) \xB7 Enter to schedule \xB7 Esc to cancel");
    if (ch === "e") {
      const r = this.selectedReminder();
      if (!r) return Promise.resolve();
      const text = cleanText(r.text, Number.MAX_SAFE_INTEGER);
      return this.startInput("edit", `edit [${shortId(r.id)}]`, "Enter to save (every 3rd edit costs 1) \xB7 Esc to cancel", { buffer: text, targetId: r.id, originalText: text, version: this.state.version });
    }
    if (ch === "t") {
      const r = this.selectedReminder();
      if (!r) return Promise.resolve();
      return this.startInput("time", `time [${shortId(r.id)}]`, "30m, 2h, 1d or clear \xB7 Enter to save (every 3rd edit costs 1) \xB7 Esc to cancel", { targetId: r.id, version: this.state.version });
    }
    if (ch === "a") return this.toggleDone();
    if (ch === "k") return this.ackSelected();
    if (ch === "K") return this.ackAll();
    if (ch === "x") return this.startConfirm("pop");
    if (ch === "d") return this.startConfirm("dequeue");
    if (ch === "b") return this.buy();
    return Promise.resolve();
  }
  loginKey(key) {
    const l = this.state.login;
    if (key.name === "escape" || key.name === "ctrl-c") return this.quit();
    if (l.busy) return Promise.resolve();
    if (key.name === "tab" || key.name === "up" || key.name === "down") {
      this.switchField(l.field === "email" ? "password" : "email");
      return Promise.resolve();
    }
    if (key.name === "enter") {
      if (l.field === "email") {
        this.switchField("password");
        return Promise.resolve();
      }
      return this.submitLogin();
    }
    const line2 = { buffer: l[l.field], cursor: l.cursor };
    if (editLine(line2, key)) {
      l[l.field] = line2.buffer;
      l.cursor = line2.cursor;
      this.changed();
    }
    return Promise.resolve();
  }
  switchField(field) {
    const l = this.state.login;
    l.field = field;
    l.cursor = [...l[field]].length;
    this.changed();
  }
  /** `client.login` saves the credentials through its onCredentials callback, exactly as `mokkan login` does. */
  submitLogin() {
    const l = this.state.login;
    const email = l.email.trim();
    if (!EMAIL_RE.test(email)) {
      l.error = { text: "Enter an email address.", tone: "red" };
      this.switchField("email");
      return Promise.resolve();
    }
    if (l.password === "") {
      l.error = { text: "Enter your password.", tone: "red" };
      this.changed();
      return Promise.resolve();
    }
    l.busy = true;
    l.error = { text: "Logging in\u2026", tone: "dim" };
    this.changed();
    return this.enqueue(async () => {
      try {
        const creds = await this.client.login(email, l.password);
        this.state.email = creds.email;
        this.state.screen = "dashboard";
        this.state.login = emptyLogin();
        this.changed();
        await this.doRefresh();
      } catch (err) {
        l.busy = false;
        l.password = "";
        l.field = "password";
        l.cursor = 0;
        const hint = err instanceof ApiError ? apiErrorHint(err) : null;
        l.error = { text: hint ? `${errorText(err)} ${hint}` : errorText(err), tone: "red" };
        this.changed();
      }
    });
  }
  quit() {
    this.exitCode = 0;
    this.changed();
    return Promise.resolve();
  }
  move(delta) {
    const s = this.state;
    const n = this.rows().length;
    s.selected = delta === -Infinity ? 0 : delta === Infinity ? n - 1 : s.selected + delta;
    this.clampSelection();
    this.changed();
    return Promise.resolve();
  }
  /** Digits select a row of the current view; one that is not there is ignored. */
  jump(index) {
    if (index >= this.rows().length) return Promise.resolve();
    this.state.selected = index;
    this.clampSelection();
    this.changed();
    return Promise.resolve();
  }
  switchView() {
    const s = this.state;
    s.tab = s.tab === "stack" ? "done" : "stack";
    s.selected = 0;
    s.scroll = 0;
    this.changed();
    if (s.tab !== "done" || s.done !== null) return Promise.resolve();
    return this.enqueue(async () => {
      s.done = (await this.client.list("done")).reminders;
      this.clampSelection();
      this.changed();
    });
  }
  activeRows() {
    return this.state.reminders.filter((r) => ACTIVE_STATES.has(r.state));
  }
  /**
   * The selected reminder for e, t, k (and, with `inDone`, a); sets the message and returns null when there is none
   * to change.
   */
  selectedReminder(inDone = false) {
    const s = this.state;
    if (s.tab === "done" && !inDone) {
      this.say("Press s for the stack to change reminders.", "yellow");
      return null;
    }
    const r = this.rows()[s.selected];
    if (!r) {
      this.say("Nothing selected.", "yellow");
      return null;
    }
    return r;
  }
  startInput(purpose, label, hint, extra = {}) {
    const buffer = extra.buffer ?? "";
    this.state.message = null;
    this.state.mode = { kind: "input", purpose, label, hint, buffer, cursor: [...buffer].length, ...extra };
    this.changed();
    return Promise.resolve();
  }
  inputKey(mode, key) {
    if (key.name === "ctrl-c") return this.quit();
    if (key.name === "escape") {
      this.state.mode = { kind: "normal" };
      this.changed();
      return Promise.resolve();
    }
    if (key.name === "enter") return this.submitInput(mode);
    if (editLine(mode, key)) this.changed();
    return Promise.resolve();
  }
  submitInput(mode) {
    const s = this.state;
    const text = mode.buffer.trim();
    if (text === "") {
      s.mode = { kind: "normal" };
      this.changed();
      return Promise.resolve();
    }
    switch (mode.purpose) {
      case "push":
        return this.action(async () => {
          const res = await this.client.push(text);
          this.say(`Pushed [${shortId(res.reminder.id)}] ${res.reminder.text}`, "green");
        });
      case "in": {
        const space = text.search(/\s/);
        const word = space === -1 ? text : text.slice(0, space);
        const rest = space === -1 ? "" : text.slice(space + 1).trim();
        const seconds = this.parseDurationOrSay(word);
        if (seconds === null) return Promise.resolve();
        if (rest === "") {
          this.say("Add the reminder text after the duration.", "red");
          return Promise.resolve();
        }
        const now = this.now();
        const dueAt = new Date(now.getTime() + seconds * 1e3);
        if (!Number.isFinite(dueAt.getTime())) {
          this.say("duration is too large", "red");
          return Promise.resolve();
        }
        return this.action(async () => {
          const res = await this.client.push(rest, dueAt);
          this.say(`Scheduled [${shortId(res.reminder.id)}] "${res.reminder.text}" for ${dueAt.toISOString()} (${formatRelative(dueAt, now)})`, "green");
        });
      }
      case "edit":
        if (text === mode.originalText) {
          s.mode = { kind: "normal" };
          this.say("Unchanged.", "dim");
          return Promise.resolve();
        }
        return this.action(async () => {
          const res = await this.client.editReminder(mode.targetId, { text }, mode.version ?? void 0);
          this.say(`Edited [${shortId(res.reminder.id)}] ${res.reminder.text}`, "green");
        }, mode);
      case "time": {
        let dueAt = null;
        if (text !== "clear") {
          const seconds = this.parseDurationOrSay(text);
          if (seconds === null) return Promise.resolve();
          dueAt = new Date(this.now().getTime() + seconds * 1e3);
          if (!Number.isFinite(dueAt.getTime())) {
            this.say("duration is too large", "red");
            return Promise.resolve();
          }
        }
        const now = this.now();
        return this.action(async () => {
          const res = await this.client.editReminder(mode.targetId, { due_at: dueAt }, mode.version ?? void 0);
          const r = res.reminder;
          const when = r.due_at ? `(due ${r.due_at}, ${formatRelative(new Date(r.due_at), now)})` : "(time cleared)";
          this.say(`Edited [${shortId(r.id)}] ${r.text} ${when}`, "green");
        }, mode);
      }
    }
  }
  /** `parseDuration`, with its error shown in the message line (the input stays open). */
  parseDurationOrSay(word) {
    try {
      return parseDuration(word);
    } catch (err) {
      this.say(errorText(err), "red");
      return null;
    }
  }
  /**
   * Leaves input or confirm mode, runs one server call, then refreshes. Failures become messages through `fail`.
   * `reopen`: the edit or time input to bring back, typed text and all, when the list changed under it.
   */
  action(work, reopen) {
    this.state.mode = { kind: "normal" };
    this.changed();
    return this.enqueue(async () => {
      try {
        await work();
      } catch (err) {
        await this.fail(err);
        const s = this.state;
        if (reopen && isStale(err) && s.screen === "dashboard" && s.mode.kind === "normal") {
          s.mode = { ...reopen, version: s.version };
          this.changed();
        }
        return;
      }
      await this.doRefresh();
    });
  }
  startConfirm(action) {
    const list = this.activeRows();
    const target = action === "pop" ? list[0] : list[list.length - 1];
    if (!target) {
      this.say("The stack is empty.");
      return Promise.resolve();
    }
    this.state.message = null;
    this.state.mode = { kind: "confirm", action, text: target.text, version: this.state.version };
    this.changed();
    return Promise.resolve();
  }
  confirmKey(mode, key) {
    if (key.name === "ctrl-c") return this.quit();
    if (key.name !== "char" || key.ch !== "y") {
      this.state.mode = { kind: "normal" };
      this.changed();
      return Promise.resolve();
    }
    const version = mode.version ?? void 0;
    return this.action(async () => {
      const res = mode.action === "pop" ? await this.client.pop(version) : await this.client.dequeue(version);
      this.say(`${mode.action === "pop" ? "Popped" : "Dequeued"} [${shortId(res.reminder.id)}] ${res.reminder.text}`, "green");
    });
  }
  /** `a`: finishes the selected reminder, or in the done view reopens it, as `mokkan done` / `mokkan undone` do. */
  toggleDone() {
    const r = this.selectedReminder(true);
    if (!r) return Promise.resolve();
    const done = this.state.tab !== "done";
    const version = this.state.version ?? void 0;
    return this.action(async () => {
      const res = await this.client.setDone(r.id, done, version);
      this.say(`${done ? "Done" : "Reopened"} [${shortId(res.reminder.id)}] ${res.reminder.text}`, "green");
    });
  }
  ackSelected() {
    const r = this.selectedReminder();
    if (!r) return Promise.resolve();
    const version = this.state.version ?? void 0;
    return this.action(async () => {
      const res = await this.client.ack([r.id], version);
      this.say(`Acknowledged ${res.acknowledged.length} reminder(s).`, "green");
    });
  }
  ackAll() {
    return this.action(async () => {
      const res = await this.client.ack("all");
      this.say(`Acknowledged ${res.acknowledged.length} reminder(s).`, "green");
    });
  }
  /**
   * Same rules as `mokkan buy`: only a Stripe Checkout address is opened. The link does not fit the message line,
   * so when it cannot be opened the message points to `mokkan buy --no-open`, which prints it.
   */
  buy() {
    return this.action(async () => {
      let res;
      try {
        res = await this.client.checkout();
      } catch (err) {
        if (err instanceof ApiError && err.status === 404) {
          this.say("Billing is not enabled on this server.", "red");
          return;
        }
        throw err;
      }
      if (!isTrustedCheckoutUrl(res.url)) {
        this.say("Checkout link is not a Stripe address. Run: mokkan buy --no-open to see it.");
        return;
      }
      let opened = false;
      try {
        opened = this.openUrl?.(res.url) ?? false;
      } catch {
      }
      this.say(opened ? "Opened Stripe Checkout in your browser; the balance updates after payment." : "Could not open a browser here. Run: mokkan buy --no-open (prints the link).");
    });
  }
  listHeight() {
    return Math.max(1, this.size.rows - CHROME_ROWS);
  }
  clampSelection() {
    const s = this.state;
    const n = this.rows().length;
    const h = this.listHeight();
    s.selected = n === 0 ? 0 : Math.min(Math.max(0, s.selected), n - 1);
    if (s.selected < s.scroll) s.scroll = s.selected;
    if (s.selected >= s.scroll + h) s.scroll = s.selected - h + 1;
    s.scroll = Math.max(0, Math.min(s.scroll, Math.max(0, n - h)));
  }
  changed() {
    this.onChange();
  }
  say(text, tone = "plain") {
    this.state.message = { text, tone };
    this.changed();
  }
  /** Every server call runs here, one after another. `work` failures become messages through `fail`. */
  enqueue(work) {
    const run2 = this.queue.then(() => work().catch((err) => this.fail(err)));
    this.queue = run2.catch(() => void 0);
    return run2;
  }
  async doRefresh() {
    const s = this.state;
    if (s.screen !== "dashboard" || this.exitCode !== null) return;
    s.refreshing = true;
    this.changed();
    try {
      const [first, me, , done] = await Promise.all([
        this.client.list("all"),
        this.client.me().catch(() => null),
        this.client.heartbeat("ui").catch(() => null),
        s.tab === "done" || s.done !== null ? this.client.list("done") : null
      ]);
      const list = await this.deliverDue(first.reminders) ? await this.client.list("all") : first;
      const keep = this.rows()[s.selected]?.id;
      s.reminders = list.reminders;
      s.version = list.version;
      s.fetchedAt = this.now();
      s.error = null;
      if (typeof me?.credit_balance === "number") s.credits = me.credit_balance;
      if (done) s.done = done.reminders;
      const idx = keep === void 0 ? -1 : this.rows().findIndex((r) => r.id === keep);
      if (idx !== -1) s.selected = idx;
      this.clampSelection();
    } catch (err) {
      if (this.sessionLost(err)) {
        this.toLogin("Session expired, log in again.");
        return;
      }
      s.error = err instanceof NetworkError ? { kind: "offline", message: err.message } : { kind: "error", message: errorText(err) };
    } finally {
      s.refreshing = false;
      this.changed();
    }
  }
  /**
   * Reminders shown here count as shown: due ones in `reminders` are marked delivered, like the hooks and
   * `mokkan watch` do. Not in the done view, which does not show them. Returns whether the server took the call.
   */
  async deliverDue(reminders) {
    if (this.state.tab === "done") return false;
    const ids = reminders.filter((r) => r.state === "due" && !this.delivered.has(r.id)).map((r) => r.id);
    if (ids.length === 0) return false;
    for (const id of ids) this.delivered.add(id);
    try {
      await this.client.deliver(ids);
    } catch (err) {
      if (this.sessionLost(err)) throw err;
      for (const id of ids) this.delivered.delete(id);
      return false;
    }
    return true;
  }
  sessionLost(err) {
    return err instanceof SessionExpiredError || err instanceof ApiError && err.code === "no_credentials";
  }
  /** The client has already removed the dead credentials; show the login screen with a clean slate. */
  toLogin(message) {
    const s = this.state;
    s.screen = "login";
    s.login = emptyLogin();
    s.login.error = { text: message, tone: "red" };
    s.reminders = [];
    s.done = null;
    s.version = null;
    s.selected = 0;
    s.scroll = 0;
    s.email = "";
    s.credits = null;
    s.fetchedAt = null;
    s.error = null;
    s.message = null;
    s.mode = { kind: "normal" };
    this.delivered.clear();
    this.changed();
  }
  /** Maps a failed server call to the message line; only a lost session changes the screen. */
  async fail(err) {
    if (this.sessionLost(err)) {
      this.toLogin("Session expired, log in again.");
      return;
    }
    if (err instanceof NetworkError) {
      this.say(`Server unreachable: ${err.message}`, "red");
      return;
    }
    if (err instanceof ApiError) {
      if (isStale(err)) {
        await this.doRefresh();
        this.say("The list changed, try again.", "yellow");
        return;
      }
      if (err.status === 409 && err.code === "not_editable") {
        this.say("This reminder was already shown or emailed, so its time can no longer be changed.", "red");
        return;
      }
      if (err.status === 404 && err.code === "empty") {
        this.say("The stack is empty.");
        return;
      }
      const hint = apiErrorHint(err);
      let text = hint ? `${err.message} ${hint}` : err.message;
      if (err.status === 402 && err.code === "insufficient_credits" && !text.includes("mokkan buy")) text += " Run: mokkan buy";
      this.say(text, "red");
      return;
    }
    this.say(errorText(err), "red");
  }
};

// src/tui/terminal.ts
import { writeSync as writeSync2 } from "node:fs";

// src/tui/keys.ts
var PASTE_START = "\x1B[200~";
var PASTE_END = "\x1B[201~";
var SEQUENCES = {
  "\x1B[A": "up",
  "\x1B[B": "down",
  "\x1B[C": "right",
  "\x1B[D": "left",
  "\x1BOA": "up",
  "\x1BOB": "down",
  "\x1BOC": "right",
  "\x1BOD": "left",
  "\x1B[H": "home",
  "\x1B[F": "end",
  "\x1B[1~": "home",
  "\x1B[4~": "end",
  "\x1BOH": "home",
  "\x1BOF": "end",
  "\x1B[3~": "delete"
};
var SINGLE = {
  "\r": "enter",
  "\n": "enter",
  "	": "tab",
  "\x7F": "backspace",
  "\b": "backspace",
  "": "ctrl-c",
  "": "ctrl-u"
};
var isControl = (cp) => cp < 32 || cp >= 127 && cp <= 159;
var INCOMPLETE_TAIL = /\x1b(?:\[[\x20-\x3f]*|O)?$/;
var KeyDecoder = class {
  /** The cleaned text of the paste being read, or null outside a paste. */
  paste = null;
  /** The incomplete escape sequence held back from the end of the last chunk. */
  pending = "";
  feed(chunk) {
    const input = this.pending + chunk;
    const tail = INCOMPLETE_TAIL.exec(input)?.[0] ?? "";
    this.pending = tail;
    return this.decode(input.slice(0, input.length - tail.length));
  }
  /**
   * Decodes the held-back tail as if the input ended there: a lone ESC is `escape`, an incomplete sequence is
   * dropped. Inside a paste nothing changes (a paste never holds a real Esc press), so an end marker split across
   * chunks still ends it.
   */
  flush() {
    if (this.paste !== null) return [];
    const rest = this.pending;
    this.pending = "";
    return this.decode(rest);
  }
  decode(chunk) {
    const keys = [];
    let i = 0;
    while (i < chunk.length) {
      if (this.paste !== null) {
        const end = chunk.indexOf(PASTE_END, i);
        this.paste += pasteText(end === -1 ? chunk.slice(i) : chunk.slice(i, end));
        if (end === -1) return keys;
        if (this.paste !== "") keys.push({ name: "paste", text: this.paste });
        this.paste = null;
        i = end + PASTE_END.length;
        continue;
      }
      const c = chunk[i];
      if (c === "\x1B") {
        if (chunk.startsWith(PASTE_START, i)) {
          this.paste = "";
          i += PASTE_START.length;
          continue;
        }
        const seq = Object.keys(SEQUENCES).find((s) => chunk.startsWith(s, i));
        if (seq) {
          keys.push({ name: SEQUENCES[seq] });
          i += seq.length;
          continue;
        }
        if (chunk[i + 1] !== "[" && chunk[i + 1] !== "O") keys.push({ name: "escape" });
        i += unknownSequenceLength(chunk, i);
        continue;
      }
      const single = SINGLE[c];
      if (single) {
        keys.push({ name: single });
        i += 1;
        continue;
      }
      const cp = chunk.codePointAt(i);
      const text = String.fromCodePoint(cp);
      i += text.length;
      if (!isControl(cp)) keys.push({ name: "char", ch: text });
    }
    return keys;
  }
};
function pasteText(text) {
  let out = "";
  let i = 0;
  while (i < text.length) {
    if (text[i] === "\x1B") {
      i += unknownSequenceLength(text, i);
      continue;
    }
    if (text.startsWith("\r\n", i)) {
      out += " ";
      i += 2;
      continue;
    }
    const cp = text.codePointAt(i);
    const c = String.fromCodePoint(cp);
    i += c.length;
    if (c === "\r" || c === "\n" || c === "	") out += " ";
    else if (!isControl(cp)) out += c;
  }
  return out;
}
function unknownSequenceLength(chunk, at) {
  const next = chunk[at + 1];
  if (next === "[") {
    let j = at + 2;
    while (j < chunk.length && chunk.charCodeAt(j) >= 32 && chunk.charCodeAt(j) <= 63) j++;
    return Math.min(chunk.length, j + 1) - at;
  }
  if (next === "O") return Math.min(chunk.length, at + 3) - at;
  return 1;
}

// src/tui/terminal.ts
var ENTER_SCREEN = "\x1B[?1049h\x1B[H\x1B[2J\x1B[?25l\x1B[?2004h";
var LEAVE_SCREEN = "\x1B[?2004l\x1B[0m\x1B[?25h\x1B[?1049l";
var ESC_FLUSH_MS = 50;
async function runTerminal(app, io, tty) {
  let done;
  const finished = new Promise((resolve) => {
    done = resolve;
  });
  const wake = () => {
    if (app.exitCode !== null) done();
  };
  let pending = null;
  let flushTimer = null;
  let left = false;
  const draw = () => {
    if (pending !== null) clearTimeout(pending);
    pending = null;
    if (left) return;
    const size = tty.size();
    app.setSize(size);
    const frame = app.render(size, io.now());
    const cursor = cursorPosition(app.state, size);
    const place = cursor ? `\x1B[${cursor.row};${cursor.column}H\x1B[?25h` : "\x1B[?25l";
    io.stdout(`\x1B[H${frame.map((l) => `\x1B[2K${l}`).join("\r\n")}${place}`);
  };
  const scheduleDraw = () => {
    if (pending === null && !left) pending = setTimeout(draw, 0);
  };
  const restoreOnExit = () => {
    try {
      tty.setRawMode(false);
    } catch {
    }
    try {
      writeSync2(1, LEAVE_SCREEN);
    } catch {
    }
  };
  const onSignal = () => {
    app.exitCode = 0;
    wake();
  };
  const report = (err) => {
    app.state.message = { text: errorText(err), tone: "red" };
    scheduleDraw();
  };
  const dispatch = (keys) => {
    for (const key of keys) {
      if (app.exitCode !== null) return;
      void app.handleKey(key).catch(report);
    }
  };
  const decoder = new KeyDecoder();
  const flush = () => {
    flushTimer = null;
    dispatch(decoder.flush());
  };
  app.onChange = () => {
    scheduleDraw();
    wake();
  };
  let unData = () => void 0;
  let unResize = () => void 0;
  let timer;
  try {
    io.stdout(ENTER_SCREEN);
    tty.setRawMode(true);
    unData = tty.onData((chunk) => {
      dispatch(decoder.feed(chunk));
      if (flushTimer !== null) clearTimeout(flushTimer);
      flushTimer = setTimeout(flush, ESC_FLUSH_MS);
    });
    unResize = tty.onResize(scheduleDraw);
    process.once("exit", restoreOnExit);
    process.once("SIGTERM", onSignal);
    process.once("SIGINT", onSignal);
    process.once("SIGHUP", onSignal);
    timer = setInterval(() => {
      void app.refresh().catch(report);
    }, REFRESH_INTERVAL_MS);
    draw();
    void app.refresh().catch(report);
    wake();
    await finished;
  } finally {
    left = true;
    app.onChange = () => void 0;
    if (timer !== void 0) clearInterval(timer);
    if (pending !== null) clearTimeout(pending);
    if (flushTimer !== null) clearTimeout(flushTimer);
    unData();
    unResize();
    process.off("exit", restoreOnExit);
    process.off("SIGTERM", onSignal);
    process.off("SIGINT", onSignal);
    process.off("SIGHUP", onSignal);
    try {
      tty.setRawMode(false);
    } finally {
      io.stdout(LEAVE_SCREEN);
    }
  }
  return app.exitCode ?? 0;
}

// src/commands/ui.ts
async function uiCommand(ctx) {
  const { io, client } = ctx;
  if (!io.isTTY || !io.tty) throw new UserError("mokkan ui needs an interactive terminal.");
  const app = new TuiApp({
    client,
    email: client.email,
    host: new URL(client.baseUrl).host,
    now: ctx.now,
    openUrl: io.openUrl
  });
  return runTerminal(app, io, io.tty);
}

// src/hooks.ts
import { appendFileSync, mkdirSync as mkdirSync2, readFileSync as readFileSync2, writeFileSync as writeFileSync2 } from "node:fs";
import path2 from "node:path";
var HOOK_BUDGET_MS = 8e3;
var DELIVER_MIN_REMAINING_MS = 1500;
var NOT_LOGGED_IN_LOG_INTERVAL_MS = 3600 * 1e3;
function parseHookInput(raw) {
  if (raw.trim() === "") return {};
  try {
    const value = JSON.parse(raw);
    return typeof value === "object" && value !== null ? value : {};
  } catch {
    return {};
  }
}
function formatStopDecision(due) {
  const reason = [
    "Reminders due (from the mokkan server):",
    ...due.map(formatReminderLine),
    `Tell the user these reminders verbatim, then remind them to ${ACK_HINT}. Then stop.`
  ].join("\n");
  const systemMessage = `${due.length} reminder(s) due \u2014 see reply`;
  return `${JSON.stringify({ decision: "block", reason, systemMessage })}
`;
}
function appendHookLog(env, kind, message) {
  const file = hookLogPath(env);
  mkdirSync2(path2.dirname(file), { recursive: true, mode: 448 });
  appendFileSync(file, `${(/* @__PURE__ */ new Date()).toISOString()} ${kind} ${message}
`, { mode: 384 });
}
function notifiedMarkerPath(env, suffix = "") {
  return `${hookLogPath(env)}${suffix}.notified`;
}
function notifiedRecently(env, suffix = "") {
  try {
    const at = Date.parse(readFileSync2(notifiedMarkerPath(env, suffix), "utf8").trim());
    const age = Date.now() - at;
    return Number.isFinite(at) && age >= 0 && age < NOT_LOGGED_IN_LOG_INTERVAL_MS;
  } catch {
    return false;
  }
}
function markNotified(env, suffix = "") {
  writeFileSync2(notifiedMarkerPath(env, suffix), `${(/* @__PURE__ */ new Date()).toISOString()}
`, { mode: 384 });
}
function safeAppendHookLog(env, kind, err) {
  try {
    if (err instanceof SessionExpiredError) {
      appendHookLog(env, kind, "session expired; run: mokkan login");
      markNotified(env);
      return;
    }
    if (err instanceof ApiError && err.code === "no_credentials") {
      if (notifiedRecently(env)) return;
      appendHookLog(env, kind, err.message);
      markNotified(env);
      return;
    }
    if (err instanceof ApiError && err.status === 402) {
      if (notifiedRecently(env, ".402")) return;
      appendHookLog(env, kind, err.message);
      markNotified(env, ".402");
      return;
    }
    appendHookLog(env, kind, err instanceof Error ? err.message : String(err));
  } catch {
  }
}
async function runHook(ctx, kind, input, deadlineAt = Infinity) {
  const { client } = ctx;
  const deliver = async (ids) => {
    if (ids.length > 0 && deadlineAt - Date.now() >= DELIVER_MIN_REMAINING_MS) await client.deliver(ids);
  };
  await client.heartbeat("claude-code", input.session_id);
  const pending = await client.pending();
  const dueIds = pending.due.map((r) => r.id);
  if (kind === "session-start") {
    const block = formatPending(pending);
    await deliver(dueIds);
    return block;
  }
  if (input.stop_hook_active === true || dueIds.length === 0) return "";
  await deliver(dueIds);
  return formatStopDecision(pending.due);
}
async function hookCommand(ctx, args, deadlineAt = Infinity) {
  const kind = args[0];
  if (kind !== "session-start" && kind !== "stop") throw new UserError("Usage: mokkan hook session-start|stop");
  try {
    const input = parseHookInput(await ctx.io.readStdin());
    ctx.io.stdout(await runHook(ctx, kind, input, deadlineAt));
  } catch (err) {
    safeAppendHookLog(ctx.io.env, kind, err);
  }
  return 0;
}

// src/watcher.ts
var DEFAULT_INTERVAL_SECONDS = 60;
var MIN_INTERVAL_SECONDS = 5;
async function watchOnce(ctx) {
  await ctx.client.heartbeat("watcher");
  const pending = await ctx.client.pending();
  if (pending.due.length === 0) return 0;
  ctx.io.stdout(`${ctx.now().toISOString()} reminders due:
${pending.due.map(formatReminderLine).join("\n")}
`);
  await ctx.client.deliver(pending.due.map((r) => r.id));
  return pending.due.length;
}
async function watchCommand(ctx) {
  const raw = ctx.flags.interval;
  const interval = raw === void 0 ? DEFAULT_INTERVAL_SECONDS : Number(raw);
  if (!Number.isInteger(interval) || interval < MIN_INTERVAL_SECONDS) {
    throw new UserError(`--interval must be a whole number of seconds, at least ${MIN_INTERVAL_SECONDS}`);
  }
  if (!ctx.client.hasCredentials()) throw new UserError("Not logged in. Run: mokkan login");
  const once = ctx.flags.once === true;
  const stop = new AbortController();
  const onSignal = () => {
    stop.abort();
  };
  process.once("SIGINT", onSignal);
  process.once("SIGTERM", onSignal);
  try {
    if (!once) ctx.io.stderr(`mokkan watch: polling ${ctx.client.baseUrl} every ${interval}s (Ctrl-C to stop)
`);
    while (!stop.signal.aborted) {
      try {
        await watchOnce(ctx);
      } catch (err) {
        if (err instanceof ApiError && err.code === "no_credentials" || err instanceof SessionExpiredError) throw err;
        ctx.io.stderr(`${ctx.now().toISOString()} watch error: ${err instanceof Error ? err.message : String(err)}
`);
      }
      if (once) break;
      await ctx.io.sleep(interval * 1e3, stop.signal);
    }
  } finally {
    process.off("SIGINT", onSignal);
    process.off("SIGTERM", onSignal);
  }
  return 0;
}

// src/statusline-remove.ts
import { constants, copyFileSync, existsSync as existsSync2, readFileSync as readFileSync3, realpathSync, renameSync as renameSync2, statSync as statSync2, unlinkSync as unlinkSync2, writeFileSync as writeFileSync3 } from "node:fs";
import { homedir as homedir2 } from "node:os";
import path3 from "node:path";
function statuslineCommand(io, args) {
  if (!args.includes("--remove")) {
    if (io.isTTY) io.stdout("mokkan 0.3.0 has no status line. `mokkan statusline --remove` takes an earlier version's out of settings.json and ~/.tmux.conf.\n");
    return 0;
  }
  const dryRun = args.includes("--dry-run");
  const now = io.now();
  const lines = [...removeClaude(io.env, now, dryRun), ...removeTmux(io.env, now, dryRun), ...removeStableCopy(io.env, dryRun)];
  if (dryRun) lines.push("Dry run: nothing was written.");
  io.stdout(`${lines.join("\n")}
`);
  return 0;
}
var TMUX_BEGIN = "# >>> mokkan status line >>>";
var TMUX_END = "# <<< mokkan status line <<<";
function home(env) {
  return env.HOME && env.HOME !== "" ? env.HOME : homedir2();
}
function claudeSettingsPath(env) {
  const dir = env.CLAUDE_CONFIG_DIR && env.CLAUDE_CONFIG_DIR !== "" ? env.CLAUDE_CONFIG_DIR : path3.join(home(env), ".claude");
  return path3.join(dir, "settings.json");
}
function tmuxConfPath(env) {
  const classic = path3.join(home(env), ".tmux.conf");
  const xdgBase = env.XDG_CONFIG_HOME && env.XDG_CONFIG_HOME !== "" ? env.XDG_CONFIG_HOME : path3.join(home(env), ".config");
  const xdg = path3.join(xdgBase, "tmux", "tmux.conf");
  return !existsSync2(classic) && existsSync2(xdg) ? xdg : classic;
}
function stableCliPath(env) {
  const base = env.XDG_DATA_HOME && env.XDG_DATA_HOME !== "" ? env.XDG_DATA_HOME : path3.join(home(env), ".local", "share");
  return path3.join(base, "mokkan", "mokkan.mjs");
}
function replaceFile(file, content, now) {
  let target = file;
  try {
    target = realpathSync(file);
  } catch {
  }
  const mode = statSync2(target).mode & 511;
  const stamp = now.toISOString().replace(/\.\d+Z$/, "Z").replace(/[-:]/g, "");
  let bak = `${file}.mokkan-bak-${stamp}`;
  for (let n = 1; existsSync2(bak); n++) bak = `${file}.mokkan-bak-${stamp}-${n}`;
  copyFileSync(file, bak, constants.COPYFILE_EXCL);
  const tmp = `${target}.${process.pid}.tmp`;
  writeFileSync3(tmp, content, { mode });
  renameSync2(tmp, target);
  return bak;
}
var isMokkanCommand = (command) => /(^|[\s/])(mokkan|mokkan\.mjs|cli\.m?js)\s+statusline(\s|$)/.test(command) && command.includes("mokkan");
function removeClaude(env, now, dryRun) {
  const file = claudeSettingsPath(env);
  if (!existsSync2(file)) return [];
  const text = readFileSync3(file, "utf8");
  let settings;
  try {
    settings = JSON.parse(text);
  } catch {
    return [`Claude Code: ${file} is not valid JSON; left alone.`];
  }
  if (typeof settings !== "object" || settings === null || Array.isArray(settings)) return [`Claude Code: ${file} does not hold a JSON object; left alone.`];
  const current = settings.statusLine;
  if (current === void 0) return [`Claude Code: no status line in ${file}; nothing to remove.`];
  const cmd = typeof current === "object" && current !== null ? current.command : void 0;
  if (typeof cmd !== "string" || !isMokkanCommand(cmd)) return [`Claude Code: the status line in ${file} is not mokkan's; left alone.`];
  if (dryRun) return [`Claude Code: would remove the mokkan status line from ${file}.`];
  const next = { ...settings };
  delete next.statusLine;
  const indent = /^[{[][^\n]*\n([ \t]+)\S/.exec(text)?.[1] ?? 2;
  const bak = replaceFile(file, `${JSON.stringify(next, null, indent)}
`, now);
  return [`Claude Code: removed the mokkan status line from ${file} (backup: ${bak}). Restart Claude Code.`];
}
function removeTmux(env, now, dryRun) {
  const file = tmuxConfPath(env);
  if (!existsSync2(file)) return [];
  const text = readFileSync3(file, "utf8");
  const lines = text.replace(/\n$/, "").split("\n");
  const trimmed = lines.map((l) => l.trimEnd());
  const start = trimmed.indexOf(TMUX_BEGIN);
  const end = trimmed.indexOf(TMUX_END);
  if (start === -1 && end === -1) return [`tmux: no mokkan block in ${file}; nothing to remove.`];
  if (start === -1 || end === -1 || end < start) return [`tmux: ${file} has an incomplete mokkan block; fix it by hand (nothing was changed).`];
  const next = [...lines.slice(0, start), ...lines.slice(end + 1)];
  if (start > 0 && next[start - 1]?.trim() === "" && (start === next.length || next[start]?.trim() === "")) next.splice(start - 1, 1);
  if (dryRun) return [`tmux: would remove the mokkan block from ${file}.`];
  const bak = replaceFile(file, next.length > 0 ? `${next.join("\n")}
` : "", now);
  return [`tmux: removed the mokkan block from ${file} (backup: ${bak}). Reload with: tmux source-file ${file}`];
}
function removeStableCopy(env, dryRun) {
  const stable = stableCliPath(env);
  if (!existsSync2(stable)) return [];
  if (dryRun) return [`CLI: would remove the copy at ${stable}.`];
  try {
    unlinkSync2(stable);
    return [`CLI: removed the copy at ${stable}.`];
  } catch (err) {
    return [`CLI: could not remove ${stable}: ${err.message}`];
  }
}

// src/cli.ts
var BOOLEAN_FLAGS = /* @__PURE__ */ new Set(["json", "all", "once", "start", "complete", "help", "exit-zero"]);
var VALUE_FLAGS = /* @__PURE__ */ new Set(["otp", "source", "interval"]);
var COMMAND_FLAGS = /* @__PURE__ */ new Map([
  ["edit", { boolean: ["clear-due"], value: ["text", "in", "at"] }],
  ["buy", { boolean: ["no-open"], value: ["pack"] }]
]);
function parseArgs(argv) {
  if (argv[0] !== "--argline") return parseWords(argv);
  const words = (argv[1] ?? "").trim().split(/\s+/).filter((w) => w !== "");
  const user = parseWords(words);
  const fixed = parseWords(["_", ...argv.slice(2)]);
  return { command: user.command, args: user.args, flags: { ...user.flags, ...fixed.flags } };
}
function parseWords(argv) {
  const flags = {};
  const positional = [];
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--") {
      positional.push(...argv.slice(i + 1));
      break;
    }
    if (arg.startsWith("--")) {
      const eq = arg.indexOf("=");
      const name = eq === -1 ? arg.slice(2) : arg.slice(2, eq);
      const scoped = positional.length > 0 ? COMMAND_FLAGS.get(positional[0]) : void 0;
      const scopedValue = scoped?.value.includes(name) === true;
      if (VALUE_FLAGS.has(name) || scopedValue) {
        if (eq !== -1) {
          flags[name] = arg.slice(eq + 1);
        } else if (i + 1 < argv.length) {
          flags[name] = argv[i + 1];
          i++;
        } else if (scopedValue) {
          flags[name] = "";
        }
        continue;
      }
      if (eq === -1 && (BOOLEAN_FLAGS.has(name) || scoped?.boolean.includes(name) === true)) {
        flags[name] = true;
        continue;
      }
    }
    positional.push(arg);
  }
  return { command: positional[0], args: positional.slice(1), flags };
}
var USAGE = `Usage: mokkan <command> [args] [--json]

  mokkan [list] [--all]           active list, top of stack first (--all adds scheduled)
  mokkan push <text>              add to the top
  mokkan pop                      remove from the top (LIFO)
  mokkan dequeue                  remove from the bottom (FIFO)
  mokkan in <duration> <text>     schedule: 30s, 10m, 2h, 1d, 1h30m
  mokkan ack <id-prefix>... | all acknowledge shown reminders (they stay on the list)
  mokkan done <id-prefix>...      finish reminders anywhere on the list (like pop, by id)
  mokkan undone <id-prefix>...    reopen finished reminders at their old position
  mokkan edit <n|id> [--all] [--in <duration> | --at <iso> | --clear-due] [new text...]
                                  change text and/or time of a reminder in one call; n = number in
                                  mokkan list (mokkan list --all with --all), or an id prefix
  mokkan pending                  due + awaiting acknowledgment
  mokkan done                     history of popped items
  mokkan ui                       full-screen view of the list with keyboard actions (needs a terminal)
  mokkan status                   server, account, session state
  mokkan buy [--pack <key>] [--no-open]
                                  buy credits: prints (and opens) a Stripe Checkout link
  mokkan balance [--json]         credit balance and recent transactions
  mokkan register [email]         create an account (--start | --complete --otp <code>)
  mokkan login [email]            log in (password from prompt or MOKKAN_PASSWORD)
  mokkan logout
  mokkan heartbeat [--source X]   tell the server a session is active
  mokkan hook session-start|stop  Claude Code hook entrypoints (JSON on stdin)
  mokkan watch [--interval N]     foreground poller (--once for a single pass)
  mokkan statusline --remove      take an earlier version's status line out of settings.json and ~/.tmux.conf

  --exit-zero                     report errors on stdout and always exit 0 (for the /mokkan slash command)
  --argline "<words>"             first argument only: split the string on whitespace and use it as the arguments
`;
function sleep(ms, signal) {
  return new Promise((resolve) => {
    const timer = setTimeout(resolve, ms);
    signal?.addEventListener("abort", () => {
      clearTimeout(timer);
      resolve();
    }, { once: true });
  });
}
function defaultTerminal() {
  const { stdin, stdout } = process;
  if (!stdin.isTTY || !stdout.isTTY) return void 0;
  return {
    size: () => ({ columns: stdout.columns || 80, rows: stdout.rows || 24 }),
    setRawMode: (on) => {
      stdin.setRawMode(on);
    },
    onData: (listener) => {
      const handler = (chunk) => {
        listener(typeof chunk === "string" ? chunk : chunk.toString("utf8"));
      };
      stdin.setEncoding("utf8");
      stdin.on("data", handler);
      stdin.resume();
      return () => {
        stdin.off("data", handler);
        stdin.pause();
      };
    },
    onResize: (listener) => {
      stdout.on("resize", listener);
      return () => {
        stdout.off("resize", listener);
      };
    }
  };
}
function defaultIO() {
  return {
    stdout: (text) => {
      process.stdout.write(text);
    },
    stderr: (text) => {
      process.stderr.write(text);
    },
    env: process.env,
    isTTY: Boolean(process.stdin.isTTY && process.stdout.isTTY),
    prompt: promptLine,
    readStdin: readAllStdin,
    now: () => /* @__PURE__ */ new Date(),
    sleep,
    openUrl: openUrlDetached,
    tty: defaultTerminal()
  };
}
var EXIT_INSUFFICIENT_CREDITS = 3;
function reportError(err, io) {
  if (err instanceof UserError || err instanceof CredentialsPermissionError) {
    io.stderr(`${err.message}
`);
    return 1;
  }
  if (err instanceof ApiError) {
    io.stderr(`${err.message}
`);
    const hint = apiErrorHint(err);
    if (hint) io.stderr(`${hint}
`);
    if (err.status === 402 && err.code === "insufficient_credits") return EXIT_INSUFFICIENT_CREDITS;
    return err.status >= 500 ? 2 : 1;
  }
  if (err instanceof NetworkError || err instanceof CredentialsLockError) {
    io.stderr(`${err.message}
`);
    return 2;
  }
  io.stderr(`Unexpected error: ${err instanceof Error ? err.message : String(err)}
`);
  return 2;
}
function makeClient(creds, io, timeoutMs, signal) {
  return new MokkanClient({
    baseUrl: resolveServerUrl(creds, io.env),
    credentials: creds,
    onCredentials: (next) => saveCredentials(next, io.env),
    reloadCredentials: () => loadCredentials(io.env),
    lock: (fn, lockSignal) => withCredentialsLock(io.env, fn, { signal: lockSignal }),
    onSessionExpired: () => clearCredentials(io.env),
    fetchImpl: io.fetchImpl,
    now: io.now,
    timeoutMs,
    signal
  });
}
async function hookEntry(args, flags, io) {
  const kind = args[0];
  if (kind !== "session-start" && kind !== "stop") {
    io.stderr("Usage: mokkan hook session-start|stop\n");
    return 1;
  }
  try {
    const deadlineAt = Date.now() + HOOK_BUDGET_MS;
    const client = makeClient(loadCredentials(io.env), io, 3e3, AbortSignal.timeout(HOOK_BUDGET_MS));
    return await hookCommand({ io, client, json: flags.json === true, flags, now: io.now }, args, deadlineAt);
  } catch (err) {
    safeAppendHookLog(io.env, kind, err);
    return 0;
  }
}
async function main(argv, io) {
  const parsed = parseArgs(argv);
  if (parsed.flags["exit-zero"] !== true) return run(parsed, io);
  await run(parsed, { ...io, stderr: io.stdout });
  return 0;
}
async function run({ command, args, flags }, io) {
  if (command === "help" || flags.help === true) {
    io.stdout(USAGE);
    return 0;
  }
  if (command === "hook") return hookEntry(args, flags, io);
  if (command === "statusline") return statuslineCommand(io, args);
  try {
    let creds;
    try {
      creds = loadCredentials(io.env);
    } catch (err) {
      if (!(err instanceof CredentialsCorruptError) || command !== "login" && command !== "logout") throw err;
      if (command === "logout") {
        clearCredentials(io.env);
        io.stdout(`Removed corrupt credentials file ${err.file}.
Logged out.
`);
        return 0;
      }
      creds = null;
    }
    const client = makeClient(creds, io, 5e3);
    const ctx = { io, client, json: flags.json === true, flags, now: io.now };
    switch (command) {
      case void 0:
      case "list":
        return await listCommand(ctx);
      case "done":
        return args.length > 0 ? await markDoneCommand(ctx, args, true) : await doneCommand(ctx);
      case "undone":
        return await markDoneCommand(ctx, args, false);
      case "pending":
        return await pendingCommand(ctx);
      case "ui": {
        const stop = new AbortController();
        try {
          return await uiCommand({ ...ctx, client: makeClient(creds, io, 5e3, stop.signal) });
        } finally {
          stop.abort();
        }
      }
      case "push":
        return await pushCommand(ctx, args);
      case "pop":
        return await takeCommand(ctx, "pop");
      case "dequeue":
        return await takeCommand(ctx, "dequeue");
      case "in":
        return await inCommand(ctx, args);
      case "ack":
        return await ackCommand(ctx, args);
      case "edit":
        return await editCommand(ctx, args);
      case "register":
        return await registerCommand(ctx, args);
      case "login":
        return await loginCommand(ctx, args);
      case "logout":
        return await logoutCommand(ctx);
      case "status":
        return await statusCommand(ctx);
      case "buy":
        return await buyCommand(ctx);
      case "balance":
        return await balanceCommand(ctx);
      case "heartbeat":
        return await heartbeatCommand(ctx);
      case "watch":
        return await watchCommand(ctx);
      default:
        throw new UserError(`Unknown command "${command}".
${USAGE}`);
    }
  } catch (err) {
    return reportError(err, io);
  }
}
var invokedDirectly = process.argv[1] !== void 0 && import.meta.url === pathToFileURL(realpathSync2(process.argv[1])).href;
if (invokedDirectly) {
  process.exitCode = await main(process.argv.slice(2), defaultIO());
}
export {
  EXIT_INSUFFICIENT_CREDITS,
  USAGE,
  defaultIO,
  main,
  parseArgs,
  sleep
};
